### ISSUE TITLE
Optimize CI/CD Build Speed

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#10]
@Zequez and I worked through getting the build process to work by force moving all dev dependencies into dependencies, but now the build process is extremely slow on vercel. Let's be precise about which dependencies we require for runtime so that the Vercel build process is not so slow!

Check commit 129ba1f21c2b7ecd266e2bf87cb2a254adcc868b

#8

**Comment by Zequez** [comment]
We can remove Next.js and replace it with Astro; we don't use any backend features anyway,

**Comment by 0x4007** [comment]
I highly recommend that this is tested after CI/CD is connected to this repo as it'll be a far less tedious process.

**Comment by sergfeldman** [comment]
This issue is assigned to @foxreymann

**Comment by sergfeldman** [comment]
@foxreymann Hey, please share the progress on this issue.

**Comment by Zequez** [comment]
@foxreymann do you have an overall idea as to what you are going to do to improve the built speed?

**Comment by 0x4007** [comment]
I was hoping that there would be some automated tool to add one dependency at a time, rebuild and see if it fails. If it fails, add another one etc.

**Comment by 0x4007** [comment]
I found a script to assist with this so I should be able to address this in my next coding session! https://github.com/ubiquity/ubiquity-dollar/blob/development/utils/remove-unused-dependencies.sh

**Comment by foxreymann** [comment]
I'm out guys, sorry
