### ISSUE TITLE
Fix availability of the pages listed on dao.ubq.fi

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/uad-ui#101]
Please, fix the availability of the pages listed on dao.ubq.fi
https://dao.ubq.fi/about
https://dao.ubq.fi/announcements
and others 
![4](https://user-images.githubusercontent.com/15567379/166317785-0994ed30-aa78-4475-b6c3-5515f3f0a839.JPG)
![5](https://user-images.githubusercontent.com/15567379/166317790-b5af1b99-4121-4dca-a2b9-ee5fc0cf6bb6.JPG)

**Comment by sergfeldman** [comment]
Not reproduced 
The root cause is undefined 
One of the hypotheses it is related to cashing mechanisms

**Comment by 0x4007** [comment]
I was investigating the logs on Vercel and here's what I understand so far:

Upon deployment, in the build process the app scrapes the Notion for the latest content. However sometimes on deployment it seems to think that some page IDs are redundant.

`"error duplicate canonical page id"`

<img width="1552" alt="Screen Shot 2022-05-05 at 02 44 02" src="https://user-images.githubusercontent.com/4975670/166807935-f41cb4ef-1bb9-4a69-8a16-c5409923762a.png">

 I simply redeployed and didn't see these errors on build so it now seems to work. I also disabled the redeploys every 6 hours - I hope that the site will still continue to automatically update! If not, then please investigate via https://github.com/pavlovcik/uad-docs/issues/4
