### ISSUE TITLE
[CONTRACTS] - PYA - Live Status

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#102]
![image](https://user-images.githubusercontent.com/4975670/146693335-9308931f-bb5c-4780-a273-d0b3990fc238.png)

Funds have been in here for a couple of days now, I would expect to see status updates. Also, quite frankly the numbers look wrong, most of everything is 0'd out.

**Comment by Zequez** [comment]
Maybe there is a conversion error when reading the contracts, I can research it.
