### ISSUE TITLE
PYA - Multi asset withdrawal

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#103]
# Multi asset withdrawal

I think we should leave open to the user to be able to determine the withdrawal asset (USDC, uAR, or a combination) upon withdrawal for enhanced UX. We can have a slider on the UI. Also, of course, the max USDC the user will be able to withdraw is the amount they farmed with their principle. 

Identical scenario with three different users with different risk tolerances:

### Risk on user
- User deposits 100 000 USDC @ 20% APY
- User waits a year.
- User decides to withdraw 100 000 USDC + 40 000 uAR

### Risk off user
- User deposits 100 000 USDC @ 20% APY
- User waits a year.
- User decides to withdraw 100 000 USDC + 20 000 USDC

### Risk average user
- User deposits 100 000 USDC @ 20% APY
- User waits a year.
- User decides to withdraw 100 000 USDC + 5 000 USDC + 12 500 uAR (The formula for this ratio should be figured out @hpiyankov)

_Originally posted by @pavlovcik in ubiquity/ubiquity-dollar-development#119

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by ryzhak** [comment]
Hi, I can take this one but I'm not really sure that this task is still valid because "split" seems to be already implemented here: https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/ProxyYieldAggregator.sol#L239

So questions:
1. Is this task valid? Or am I just misunderstood the task concerning the "split" feature?
2. What is the actual ethereum address of the PYA contract?
3. Where is the UI for PYA? I can't find it at https://uad.ubq.fi/

**Comment by 0x4007** [comment]
@ryzhak I want to send a 50 DAI + 50 UBQ bounty for you identifying that this bounty is no longer valid. It looks like it has been already handled with the "split" parameter as you highlighted and that this particular issue was forgotten about.

If you could post again your wallet address here that would be appreciated!

We didn't deploy the PYA that you linked. We only have an alpha version deployed which is disconnected from our dashboard.

**Comment by ryzhak** [comment]
@pavlovcik 

ok, got it, thank you

wallet: https://etherscan.io/address/0x165343c045a00770b61DbCa01956590cC6005666

**Comment by 0x4007** [comment]
https://etherscan.io/tx/0xb5e97b658e2af9a546664a5be81e78347dda58cb70f7a9dfd015bb1f2d5e4d75
https://etherscan.io/tx/0x1462f1bcc69768e54507ec9b2800d894433c6a114d89a7f7780488b70dbfc84d
