### ISSUE TITLE
[CONTRACTS] - DebtCouponManager V2 - 1:20 collateralization

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#104]
**Relevant links:**

- Ubiquity Treasury Address [0xefc0e701a824943b469a694ac564aa1eff7ab7dd](https://www.notion.so/a824943b469a694ac564aa1eff7ab7dd)
- DebtCouponManager address: [0x432120Ad63779897A424f7905BA000dF38A74554](https://etherscan.io/address/0x432120Ad63779897A424f7905BA000dF38A74554)

**Assumption:**

- The only place where uAD minting is happening (outside of an explicit admin call), is on the DebtCouponManager contract.
- The 1:20 collateralization can then be done as part of the DebtCouponManagerV2.

**Conversations:**

<img width="544" alt="Captura de Tela 2021-10-29 às 03 35 59" src="https://user-images.githubusercontent.com/126037/139390537-8334acd6-3b6e-4052-8e5e-929df94344f1.png">

**Questions:**

- Should the currencies we use as collateral be customizable or hardcoded into the contract?
- Should we collateral only with stablecoins, or also with non-stablecoins like ETH?
- What currencies should we consider as collateral right now?

**Conditions:**

- The collateral should be stored on the treasury address
- Currencies to consider as collateral should be customizable
    - For each coin store the token address and the Chainlink oracle address
- Collateral rate should be customizable
- Should work with both stablecoins and non-stablecoins
- Calculate the USD value of the sum of all collaterals
- During `mintClaimableDollars` limit the maximum minting so that `uAD.totalSupply()` ends up at most as the maximum rate
- During initial deployment set collateral to 1:20 rate
- During initial deployment set collateral currencies: DAI, USDT, USDC, LUSD, ETH

**Comment by hpiyankov** [comment]
1. Customizable
2. Both
3. The list of coins that you have is OK, I know @pavlovcik wants to have LUSD as well

**Comment by 0x4007** [comment]
> 1. Customizable
> 2. Both

I was under the impression we would only use stableish assets - when we enter the bear market we are gonna regret having volatile assets like ETH. Why do you want to mix it up?

> 3. The list of coins that you have is OK, I know @pavlovcik wants to have LUSD as well

I think we should have permission-less assets only, so LUSD is my favorite (they have zero governance, and are ONLY ETH backed.) Aside from that, perhaps UST.

If we want a non pegged stablecoin, we could also use RAI (ETH backed.)

MIM uses tokens that rely on USDC so no.
FRAX is backed mostly by USDC, similar to DAI so no.
FEI has to figure themselves out first so no.
