### ISSUE TITLE
[CONTRACTS] - Debt Conversion Formulas

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#105]
Taken from a Jamboard conversation with @marcomow and @Zequez, I realized that we do not currently allow for users to convert in the directions indicated in RED. We need the formulas for enhancing our internal economy's efficiency and the users' experience!

![image](https://user-images.githubusercontent.com/4975670/138823334-cf8b58c5-6be7-4420-b0ac-68358b2c4a7e.png)

- [x] uAD → uDEBT
- [ ] uAD → uAR
- [x] uAR → uAD
- [ ] uAR → uDEBT
- [ ] uBOND → uAD
- [x] uDEBT → uAD
- [ ] uDEBT → uAR

**Comment by hpiyankov** [comment]
Let's clarify first:

1. What is uBOND?
2. There is a uAD->uAR conversion, it is the same as the uAD->uDEBT conversion

From my understanding, the only missing element is uAR <-> uDEBT. 

So let's agree on the scope before moving forward.

**Comment by 0x4007** [comment]
1. uBOND is for our contributors and investors. They do not depreciate in value as a thank you. uBOND is technically the same thing as uAR, except that we will always honor uBOND 1:1 uAD conversion. uBOND should be minted directly from the admin wallet/multisig of the DAO. After full decentralization I think that uBOND will cease to exist. 
2. uDEBT doesn't depreciate in value until the moment it expires so the mechanism is different. The uAD->uAR conversion does not currently exist in the code afaik. But we need to know how many uAD can be redeemed per uAR at the moment of conversion (debt clock) ideally if you can spell it out for the engineers so they minimize the possibility of implementing the incorrect math. 

A side note but the premium that we provide for uAD->uDEBT, and uAD->uAR; shouldn't they be dynamic ideally? We could backlog it.

**Comment by hpiyankov** [comment]
1. uBOND work the same way uDEBT works without expiration. So it is always convertible 1:1. When the bond is issued it gives a premium. For example 10 000 investment at 50% premium = 15 000 uBOND. Then the holder of the bond can convert it to 1:1 uAD.
2. The way uAD is redeemed for uAR was discussed and described here - ubiquity/ubiquity-dollar-development#116
3. The last issue is the conversion between uAR and uDEBT. I suggest that:
- uDEBT CAN be converted to uAR
- uAR can NOT be converted ti uDEBT (it will be waaaay to complex with many attack vectors,so not really worth it)

The way  uDEBT can be converted to uAR proposal:
We know that uDEBT is always worth 1 uAD
We know how much uAD is 1 uAR worth at any given point in time
We know what duration of the uDEBT remains in percentage

So the conversion rate would be:

(1 uDEBT) * (Remaining duration %) * (uAR/uAD conversion rate)

Example:
- 10 000 uDEBT with a total duration of 6 months has been around for 4 months, so they have 33% duration remaining. 
- uAR/uAD exchange rate is 1.5

So the user can get: 10 000 * 33% * 1.5 = 4 950 uAR (which is currently worth 3300 uAD)

**Comment by 0x4007** [comment]
# 2022 Update

The token symbols have been updated since this issue was first created.

1. `uAR` ⮕ `uCR` (Credit)
2. `uDEBT` ⮕ `uCR-NFT` (Credit NFT)
3. `uBOND` ⮕ `uCR-NFT` (Credit NFT)

Note: `uBOND` was supposed to be "non-expiring" instead we can just mint some `uCR-NFT` to have an expiration date in the far future so that its effectively the same thing.

## Bounty Hunter Tasks

Will create new issues now.

- [ ] 1. #401
- [ ] 2. #400
