### ISSUE TITLE
[CONTRACTS] - DebtCouponManager V2 - Migrate corresponding uAR to uBOND

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#107]
Currently investors and contributors were given uAR tokens as a sort of debt. The intention was not for these to deprecate in value. Since we're adding value deprecation to uAR, we need to convert the existing uAR that were given with this intention to  the newly created uBOND token that can be exchanged 1-1 with uAD when TWAP > 1 and has priority over uAR.

# What needs to happen

- Make a list of all addresses that hold uAR distributed with this intention
- Make an admin transaction to migrate them to uBOND

**Comment by 0x4007** [comment]
Investors received UBQ
