### ISSUE TITLE
[CONTRACTS] - DebtCouponManager V2 - Create uBOND token

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#108]
It's just a regular ERC20 token that can be redeemed 1-1 to uAD when the TWAP is > 1

# What needs to happen

- Create uBOND token
- Make redeeming function for uAD 1-1 when TWAP > 1

**Comment by 0x4007** [comment]
This will simply be uCR-NFTs with an expiration time far enough in the future to consider them "non expiring"
