### ISSUE TITLE
[CONTRACTS] - DebtCouponManager V2 - Add uBOND to debt redeeming priority

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#109]
Right now while redeeming debts, uAR has priority over uDEBT.

During uDEBT redemption at `redeemCoupons` we make the following check:

```sol
require(
            autoRedeemToken.totalSupply() <= uAD.balanceOf(address(this)),
            "There aren't enough uAD to redeem currently"
        );
uint256 maxRedeemableCoupons = uAD.balanceOf(address(this)) -
            autoRedeemToken.totalSupply();
```

That should change to also sum the uBondToken total supply.

After adding the uBOND token we should instead check for the balance of the sum of both  uAR and uBOND instead.

And on the `burnAutoRedeemTokensForDollars` we should add something like:

```sol
require(
            uBondToken.totalSupply() <= uAD.balanceOf(address(this)),
            "There aren't enough uAD to redeem currently"
        );
uint256 maxRedeemableTokens = uAD.balanceOf(address(this)) -
            uBondToken.totalSupply();
```

## What needs to happen

- uBOND should be prioritized over uAR and uDEBT
- uAR should be prioritized over uDEBT
- uDEBT should be last
- Remember to convert the autoRedeemToken `totalSupply` to uAD by multiplying it by the DebtClock `rateAtBlockNumber`

**Comment by 0x4007** [comment]
uBOND removed from design
