### ISSUE TITLE
[CONTRACTS] - DebtCouponManager V2 - Update uAR-uAD minting and burning with the DebtClock

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#110]
Right now uAR is burned 1-1 with uAD when TWAP > 1; and minted 1-1 for uAD when TWAP < 1

## What should happen

- Divide the uAD burned for uAR by the DebtClock `uarRateAtBlockNumber`
- Multiply the uAR burned for uAD by the DebtClock `uarRateAtBlockNumber`

**Comment by 0x4007** [comment]
I'm not sure if we still need this issue. I don't really understand it.
