### ISSUE TITLE
[CONTRACTS] - DebtCouponManager V2 - uAR to uDEBT conversion mechanism

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#111]
Right now there is not way to convert uAR to uDEBT

## What needs to happen

- We need a function (maybe `burnAutoRedemptionForCoupons` for the sake of consistency) that takes any amount of uAR and mints the equivalent of uDEBT as if was being redeemed right there for uAD; so considering the DebtCoupon. To do this, we multiply it by the DebtClock `uarRateAtBlockNumber`

**Comment by 0x4007** [comment]
Hristo said no to this feature https://github.com/ubiquity/ubiquity-dollar/issues/105#issuecomment-1115346883
