### ISSUE TITLE
[CONTRACTS] - DebtCouponManager V2 - New uDEBT to uAR conversion mechanism

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#112]
Right now if you convert uCR-NFT to uCR with the CreditManager you get a 1-1 conversion, no mater how close the uCR-NFT token is to expiring. While if expired does not allow you to convert at all.

The relevant function is `burnCreditNftsForCredits`

## What needs to happen

- Using the CreditClock we should consider the price of the uAD-uAD-equivalent of the uCR-NFT amount (right now it converts 1-1) (this means dividing it by the CreditClock `creditRateAtBlockNumber`, the result should be a higher amount of uCR (because it's devalued))
- At mint time the conversion should be 100%
- At expiration time the conversion should be 0%
- In between we lower it linearly using the expiration time

**Comment by 0x4007** [comment]
Consolidated into issue #400
