### ISSUE TITLE
`uCR -> uAD` official exchange rate contract "DebtClock" 

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#115]
We need a new contract that helps us calculate the uAR deprecation rate.

Details about the math available on [\[0094-UBQY\] uAR simple calc](https://docs.google.com/document/d/12gGDjRw4s1TRH4mT9v3yb_TFnFDKfzKgTjTfIKtoAMM/edit)

### Policy

The R value is determined by policy and the latest policy is that `The depreciation rate of uAD is defined in such a way, that at the time of uDEBT expiration, UAR is worth 70%`

The formula to get R is the following:

`(1+R)^(blockCountIn30Days) = 1/valueAfter30Days`
`R = (1/valueAfter30Days)^(1/blockCountIn30Days)-1`

So let's say we have 194.404 blocks in 30 days. And our valueAfter30Days is 0.7 (70%):

`(1+R)^(194404) = 1/0.7`
`R = (1/0.7)^(1/194404)-1 = 0.000001835`

But we don't need to know this for the contract, we just get the R value directly.

### Context

So the initial spec of the DebtClock called for a rate that can be updated multiple times. It called for storing the block the rate is updated and the rate itself; this way we can calculate the price of uAR for any block.

However, Ben mentioned that over time, as we update the rate and the array keeps getting longer, this can cause issues with the maximum gas fees. To prevent this we'll be removing the possibility to calculate the uAR price for any block, we will only be able to get the price for any block onward since the rate was last changed; older rates won't be stored.

### Customizable Variables

**.ratePerBlock**

This is the deprecatio rate. How much uAD is deprecated on each block.

Ex: 0.05 = 5% deprecation per block

**.rateStartBlock**

This is the block height from where we start applying the rate. Before this start block we won't have price information.

**.rateStartValue**

This is the exchange rate of uAR for the start block.

### Methods

**.setRatePerBlock(ratePerBlock)**

- Should set the `ratePerBlock`
- Should set the `rateStartValue` to the current rate value before it's changed
- Should set `rateStartBlock` to the current block height
- Should be only callable by admin

**.rate(blockNumber)**

- Should return the amount of uAR you would get for 1 uAD at the specific block number.
- If blockNumber isn't given then use the current block number.
- Require that blockNumber is less than **`rateStartBlock`**

### Rate math

```tsx
rateStartValue * ( 1 / ( (1 + ratePerBlock) ^ (blockNumber - rateStartBlock) ) )
```

## To be used on:

- DebtCouponManager: Adjust the uAR minting and burning to the rate
- YieldProxy: Adjust the uAR reward minting to the rate

**Comment by hpiyankov** [comment]
I am assuming you need the math checked only in the Policy section. If this is the case - I have checked it and it's correct.

Please keep in mind that:
- This should not be calculated on 30-day increments, it is calculated block per block
- In valueAfterXDays days, both the value and the X days are currently assumptions, they need to be parameters which we can change.

**Comment by Zequez** [comment]
@hpiyankov  @zgorizzo69 I just updated the spec with a simplified version that only allows for reading the rate for blocks after the rate was last set, but doesn't need to store the list of all the times the ratesPerBlock were changed.

**Comment by 0x4007** [comment]
We should look at this as the "bank of ubiquity" charging interest on uCR holders. Basically the "interest rate" is actually just the exchange rate getting more expensive over time. 

I think we should make this logarithmic so that in the beginning it allows us to obtain a 4D chess "profit" more quickly and then over time it cools down and becomes less expensive for holders.

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by ethernomad** [comment]
I'm keen to start implementing this tomorrow. I have 7 years experience with Solidity.
Here's some of my contracts: 
https://github.com/acuity-social/acuity-atomic-swap-solidity/tree/main/src
https://github.com/acuity-social/acuity-contracts/tree/master/src

Can I be assigned to this issue?

**Comment by sergfeldman** [comment]
> I'm keen to start implementing this tomorrow. I have 7 years experience with Solidity. Here's some of my contracts: https://github.com/acuity-social/acuity-atomic-swap-solidity/tree/main/src https://github.com/acuity-social/acuity-contracts/tree/master/src
> 
> Can I be assigned to this issue?

@ethernomad You are assigned to this issue

**Comment by ethernomad** [comment]
This page: https://github.com/ubiquity/ubiquity-dollar/wiki/11.-uCR refers to both uCR and uAR. It seems these are the same thing. Is uCR the new name for uAR?

In the smart contract it is still identified as uAR:
https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/contracts/src/dollar/core/UbiquityCreditToken.sol#L8

**Comment by 0x4007** [comment]
> Is uCR the new name for uAR?

That's correct. Perhaps the information was not copied over with 100% integrity from [https://dao.ubq.fi/dollar](https://dao.ubq.fi/dollar)

**Comment by ethernomad** [comment]
This is ready for review.

Here's my Ethereum address for USDC:
0x36a7401F269555916a0243E586234D3Bbf5A0c36

**Comment by 0x4007** [comment]
Is DAI ok? We have that handy now.

> This is ready for review.
> 
> Here's my Ethereum address for USDC: 0x36a7401F269555916a0243E586234D3Bbf5A0c36

**Comment by 0x4007** [comment]
I just realized that this is a spec from last year. I asked @Zequez to see if he would be keen on lending his eyes for a review but he's not active on the project anymore. I'm personally a bit distracted with Taipei Blockchain Week but I'll prioritize and try to get you saddled up asap. Thanks a ton for your contribution!

**Comment by ethernomad** [comment]
DAI is okay thanks.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by ethernomad** [comment]
Not which issue I should work on next, please advise.

**Comment by sergfeldman** [comment]
> Not which issue I should work on next, please advise.

@ethernomad please, review currenly open issues 
https://github.com/ubiquity/ubiquity-dollar/issues/assigned/ubiquity-bounties
And we will create more issues in the near future.

**Comment by ethernomad** [comment]
Wallet address for ETH / DAI / USDC:

0x36a7401F269555916a0243E586234D3Bbf5A0c36

**Comment by 0x4007** [comment]
> Wallet address for ETH / DAI / USDC:
> 
> 
> 
> 0x36a7401F269555916a0243E586234D3Bbf5A0c36

https://etherscan.io/tx/0xfb5ca6e9b6c29f667c9e75dc4b9ce42f38cba6b20726c74f47f2ab4aa8b086b6

https://etherscan.io/tx/0x63d388534212d1ba7a253d7cc980f03b9081ab2992ebec191155b12456fe9571
