### ISSUE TITLE
Proxy Yield Aggregator "Debt Clock"

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#116]
When we deploy the global uAR "Debt Clock" (the redemption contract which accepts uAR and mints uAD) this Proxy Yield Aggregator must take this into account and mint more uAR as a reward (as they will depreciate in value.)

Either we wait to deploy with this capability OR we deploy and deprecate this contract when we figure out the "Debt Clock" system

https://github.com/ubiquity/uad-contracts/blob/4f855e56483fcbbf6ffc2f9b0ac190a9c2e8a492/contracts/YieldProxy.sol#L282

**Comment by 0x4007** [comment]
I looked through the code some more and realized the best plan is likely to be to deploy a new token contract which represents the true uAR token (perhaps `UbiquityAutoRedeemV2.sol`) 

The original `UbiquityAutoRedeem.sol` will be renamed to `uBOND` `Ubiquity Bond`.

This `UbiquityAutoRedeemV2.sol` will extend the `mint` function.

This extended mint function will have an upgradable formula, which will include the block height. This way we can calculate what the "debt clock coefficient" should be.

The purpose of the debt clock coefficient is to synchronize how many uAR is redeemable for 1 uAR at any moment in our economy.

In `YieldProxy.sol:282` `autoRedeemToken.mint(address(this), uARYield);` the returned amount should be an increasing amount over time, as uAR will lose value and the investor is measuring their APY in dollar amount. 

https://github.com/ubiquity/uad-contracts/blob/main/contracts/UbiquityAutoRedeem.sol

**Comment by 0x4007** [comment]
@zgorizzo69 proposal something like this for debt clock, instead of extending mint ```int uadAmount = burnAutoRedeemForDollar(uAR);```

**Comment by zgorizzo69** [comment]
add a formula contract to calculate 
`getUARAmountForDollar`
`getUADAmountForUAR`

**Comment by 0x4007** [comment]
@hpiyankov we need the conversion rate formula for uAR to uAD (and the reverse, for the UI) that includes blockHeight

**Comment by Zequez** [comment]
Do we need to actually override the mint function on the new token? Couldn't it just be a the regular ERC20 token, and we just make sure we take into account the multiplier during minting and during burning?
There is an `UARForDollarsCalculator` contract that can be upgraded on the Manager. Currently the `getUARAmount` function takes a `dollar` and `blockHeight` parameters and looks like this:

```sol
    function getUARAmount(uint256 dollarsToBurn, uint256 blockHeightDebt)
        external
        view
        override
        returns (uint256)
    {
        require(
            DebtCoupon(manager.debtCouponAddress()).getTotalOutstandingDebt() <
                IERC20(manager.dollarTokenAddress()).totalSupply(),
            "uAR to Dollar: DEBT_TOO_HIGH"
        );
        bytes16 coef = _coef.fromUInt().div((uint256(1 ether)).fromUInt());
        bytes16 curBlock = uint256(block.number).fromUInt();
        bytes16 multiplier = blockHeightDebt.fromUInt().div(curBlock);
        // x^a = e^(a*lnx(x)) so multiplier^(_coef) = e^(_coef*lnx(multiplier))
        bytes16 op = (coef.mul(multiplier.ln())).exp();
        uint256 res = dollarsToBurn.fromUInt().mul(op).toUInt();
        return res;
    }
```

Was that created in foreshadow of this?

**Comment by 0x4007** [comment]
lol good find but on my call with zgo he didn't mention it - was it forgotten? 😂

We don't need to override the mint function, I changed my suggestion below: 

> @zgorizzo69 proposal something like this for debt clock, instead of extending mint `int uadAmount = burnAutoRedeemForDollar(uAR);`

**Comment by hpiyankov** [comment]
> @hpiyankov we need the conversion rate formula for uAR to uAD (and the reverse, for the UI) that includes blockHeight

We already have this, for quite some time: https://docs.google.com/document/d/12gGDjRw4s1TRH4mT9v3yb_TFnFDKfzKgTjTfIKtoAMM/edit

---

> uAR also needs a premium for burning uAD, otherwise, it makes no sense.
> 
> uAR uses the same formula for premium as uDEBT, however it gets only 70% of the premium (configurable)
> 
> The depreciation rate of uAD is defined in such a way, that at the time of uDEBT expiration, UAR is worth 70% (configurable via setting the rate - R) of its original value. For example: if the expiration duration is 30 days, then we can define the needed rate  - R for the period as:
> 
> (1+R)^(blocks) = 1/0.7
> 
> If we assume 1 block per 12 seconds, in 30 days we get 216 000 blocks
> 
> Then: (1+R) ^216000 = 1.4286
> R =  0.000001651366844
> 
> The ratio of uAD/uAR starts at 1 and we define an inflation rate (the one which we derived above, for example). Then the ratio of the uAD/AR changes with each block according to the formula:
> 
> (1+R)^(elapsed blocks)
> 
> Important: R should be configurable for a given period. E.g. we should be able to change R, without this affecting negatively already existing uAR. 
> 
> If we assume a block time of 12 seconds, this gives us the following ratio per day:
> 
> 
> 
> So let’s look at an example:
> User A wants to burn 1000 uAD on day 1. The current ratio is 1:1 and we offer him 30% premium (for example). He gets 1000 * 1 * 1.3 = 1300 uAR
> On day 15 debt cycle ends, the mint cycle begins
> On day 16 the ratio is 1.19. If the user redeems his 1300 uAR at this point, he would get 1300/1.19 = 1092 uAD
> On day 31 the ratio is 1.42. If the user redeems his 1300 uAR at this point, he would get 1300/1.42 = 915 uAD
> 
> 
> Example2:
> The debt cycle has started on day 5, at a ratio of 1.048 (irrelevant for further calculations, just here to show that the 1:1 ratio is a fixed point in time and not associated with cycles)
> User B wants to burn 1000 uAD on day 10. The current ratio is 1:1.11 and we offer him a premium of (10%, since we are later in the debt cycle). He would then get: 1000 * 1.1 * 1.1 = 1210 uAR
> On day 31, the debt cycle ends, we mint and the user redeems his funds at a ratio of  1.42. He would get back 1210 / 1.42 = 852 uAD
> 
> 
>

**Comment by Zequez** [comment]
Created an issue for the DebtClock contract here ubiquity/ubiquity-dollar-development#115. We can keep this issue for adding the use that contract on the YieldProxy

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by ryzhak** [comment]
Seems that this task should be deleted as PYA is going to be removed in https://github.com/ubiquity/ubiquity-dollar/issues/292

**Comment by 0x4007** [comment]
This just needs to be re-specified but the idea will still exist. The idea is that our uCR (Credit) tokens need to have a sense of a global clock to represent its inflation. For example:

> 1 uCR is redeemable for 1 uAD .... but wait a month and it will be 1 uCR redeemable for 0.5 uAD (uCR lost half of its value)

We need to create a standard getter method for UIs and smart contracts to easily understand this conversation rate, live.

--

I need to verify if there is a more accurate bounty somewhere or if I should slightly readjust this one.

**Comment by ryzhak** [comment]
> This just needs to be re-specified but the idea will still exist. The idea is that our uCR (Credit) tokens need to have a sense of a global clock to represent its inflation. For example:
> 
> > 1 uCR is redeemable for 1 uAD .... but wait a month and it will be 1 uCR redeemable for 0.5 uAD (uCR lost half of its value)
> 
> We need to create a standard getter method for UIs and smart contracts to easily understand this conversation rate, live.
> 
> --
> 
> I need to verify if there is a more accurate bounty somewhere or if I should slightly readjust this one.

Looks like this task already exists https://github.com/ubiquity/ubiquity-dollar/issues/115

**Comment by 0x4007** [comment]
> Looks like this task already exists #115

Thanks for checking for me. So basically this just needs to be integrated with our ecosystem of products, including the new version of the pya (vaults) https://github.com/ubiquity/ubiquity-dollar/pull/267

**Comment by ethernomad** [comment]
Should I do this one next?

**Comment by sergfeldman** [comment]
> Should I do this one next?

@ethernomad Do you have any questions on the description or deliverables expected in this issue?

**Comment by 0x4007** [comment]
> Should I do this one next?

Hey @ethernomad thanks for hopping in so quickly to bid on these bounties. Apologies but all of the issues were created when we were just re-creating the repository, and there unfortunately seems to have been a bit of a mixup. It appears that both are essentially the same task. 

I think that this one just specifies that we must have a getter on the other contract that you made that will allow any UI to easily get the current value of the credit tokens.

I'll go ahead and close these issues, but please feel free to take a look at the other issues in the repo and bid on those if you're interested. Thanks again for your interest in the project!

**Comment by 0x4007** [comment]
@ethernomad I parsed through some of those old issues and made a couple new ones that are related to your work. 

#400 
#401
