### ISSUE TITLE
[CONTRACTS] - `yarn hardhat priceReset`

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#118]
This implementation doesn't make sense. Its primary purpose is to automatically set the price to 1.00 by removing uAD liquidity.

Bonus if I can input the price e.g. `yarn hardhat priceReset --to 1.001" and it'll do the math and reset to the specific price with the same logic. 

@hpiyankov let me know if you have any inputs on the reset strategy, but I believe that removing single sided liquidity is the best approach.

**Comment by hpiyankov** [comment]
@pavlovcik I feel like I am lacking context. What doesn't make sense?

**Comment by 0x4007** [comment]
@zgorizzo69 walked me through this price reset script but all he's missing is the formula to calculate how many LP tokens to remove in order to set the twap back to 1.00, according to him. 

After he has this information he can make the command line interface a one argument reset command vs how it's implemented now (a lot more than one)

**Comment by hpiyankov** [comment]
This is pretty straightforward. Since we want to reset at the best balance point (and not at the first one), essentially we need to have equal amounts of 3CRV and uAD. This means that the amount of uAD which needs to be removed from the pool is equal to:
`amt_to_remove = uAD_curr - 3CRV_curr`

So essenetially we need to remove the amount of LP tokens which allows us to remove `amt_to_remove` from the 3CRV pool.

**Comment by 0x4007** [comment]
I'll let @zgorizzo69 jump in here no point of me speculating what his questions may be

**Comment by 0x4007** [comment]
# attention bounty hunters
the hardhat task to edit is the following. it could use a ton of cleanup. the end result is that the operator should be able to simply call the task and it'll reset the price.
https://github.com/ubiquity/ubiquity-dollar-development/blob/main/contracts/dollar/tasks/priceReset.ts

the parameters should still include `--dryRun` as a safety switch

**Comment by 0x4007** [comment]
a later version of this script should consider the amount of stablecoins in the operator wallet and allow for another parameter to inject liquidity or remove liquidity based on the amount of coins in the wallet in order to stabilize the price back to 1.00.

**Comment by sergfeldman** [comment]
This bounty is taken by Liu
