### ISSUE TITLE
Gracefully show errors on the app states 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/uad-ui#126]

**Comment by sergfeldman** [comment]
- explore unhandled errors and show error message for them 
- when the smart contract is unavailable on the selected network

**Comment by sergfeldman** [comment]
Done in the pull request, waiting for the merge to the Master.

**Comment by Zequez** [comment]
I want to make sure we show an error when contract isn't available in the current network before we close this.

**Comment by 0x4007** [comment]
I voted "Impact: Small" because I understood that Impact is from a user facing perspective, and this is a developer "behind-the-scenes" type improvement. Perhaps we need clarity on the definitions.
