### ISSUE TITLE
Consolidate code of all website pages in 1 repo 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/uad-ui#145]
Background
There are some pages code of that is located in other places than https://github.com/ubiquity/ubiquity-dollar-development
The example is landing.ubq.fi 

Request
Please, consolidate the code of all website pages in 1 repo https://github.com/ubiquity/ubiquity-dollar-development

**Comment by 0x4007** [comment]
Somebody other than me should figure out how to host static pages. Then it will be solved.
