### ISSUE TITLE
Rebrand Debts into Credits

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#146]
Credits have a more positive feeling vs debts, so we're rebranding! Please reflect this in the UI.

<img width="476" alt="Screen Shot 2022-05-05 at 06 37 22" src="https://user-images.githubusercontent.com/4975670/166836587-32ff0779-59e5-4273-9278-2bd84e4c8b8d.png">

![uCR-1000x1000](https://user-images.githubusercontent.com/4975670/166836760-3bb901d6-fbd1-41ba-a326-68d0e8057dd1.png)

The raw vectors are available on this figma - check page 2
https://www.figma.com/file/t7mstvFjXU057Gr5nEx8eQ/Ubiquity-Token-Icons?node-id=124%3A30

**Comment by sergfeldman** [comment]
hey btw we’re in the process of rebranding all the debts into Ubiquity Credit (uCR) and Ubiquity Credit NFT (uCR-NFT) so this should be reflected in the UI!

**Comment by sergfeldman** [comment]
Chris will analyze and compile the questions.

**Comment by 0x4007** [comment]
uAR -> Ubiquity Credit (uCR) 
uDEBT -> Ubiquity Credit NFT (uCR-NFT)

**Comment by sergfeldman** [comment]
https://github.com/ubiquity/ubiquity-dollar-development/pull/149 Use this branch

**Comment by sergfeldman** [comment]
Waiting for the confirmation from @Zequez before closing this issue.

**Comment by Zequez** [comment]
Are we using the same icon for the fungible and non-fungible versions?

**Comment by sergfeldman** [comment]
Alex - we will use the same icon for now
