### ISSUE TITLE
add network to ui

### ISSUE THREAD

**Issue by 3commascapital** [ubiquity/uad-ui#151]
without `ethereum mainnet` visible on ui users who are on multiple evm networks using metamask may get confused. uniswap shows a red message when incorrect network is being used
https://docs.metamask.io/guide/ethereum-provider.html#chain-ids
https://docs.metamask.io/guide/ethereum-provider.html#using-the-provider

**Comment by marcomow** [comment]
thanks @3commascapital, moved the issue to the correct repository
