### ISSUE TITLE
Make "Price Stablization" Interface show up regardless of whether you have uAD in your wallet or not.

### ISSUE THREAD

**Issue by littleflute23** [ubiquity/uad-ui#160]
Right now, if you do not hold Ubiquity Dollars/Credits in your wallet the interface does not seem to show up for the web page. Please make it so that it shows up regardless. 
<img width="960" alt="2022-05-12 20_19_42-MetaMask Notification" src="https://user-images.githubusercontent.com/99516437/168188183-981c2db6-3747-49b8-860e-b1da097b9b90.png">

**Comment by myallcodebase** [comment]
It looks like it's working fine.
It's displaying all UIs although it doesn't hold Ubiquity Dollars/Credits.

![image](https://user-images.githubusercontent.com/98002862/170716039-004c3ee1-5a84-4a80-9b81-51465e5f7993.png)
