### ISSUE TITLE
Change Price Stablization Interface

### ISSUE THREAD

**Issue by littleflute23** [ubiquity/uad-ui#161]
So talked with Alex. Think we can get rid of the TWAP price and keep the 3CRV Price as the main point. Recommend changing "3-CRV Swap Price" to "Ubiquity Dollar Spot Price." For the TWAP Price, I think you can have a small question mark around "Ubiquity Dollar Spot Price" and when someone hovers over it, the menu can show the TWAP Price.

<img width="427" alt="2022-05-12 20_43_39-Dashboard _ Ubiquity Dollar" src="https://user-images.githubusercontent.com/99516437/168189536-f795cb71-a6fe-48f1-afec-d1d69ff87228.png">

Small Question Mark can look something like this. 
<img width="71" alt="2022-05-12 21_21_21-Inverse Finance - INV" src="https://user-images.githubusercontent.com/99516437/168192689-fc7b6e3f-9bbb-45a1-8bab-96d2b80481b1.png">

<img width="252" alt="2022-05-12 21_22_28-Inverse Finance - INV" src="https://user-images.githubusercontent.com/99516437/168192748-c6428818-6107-40a7-94dc-81e40a67e605.png">

**Comment by 0x4007** [comment]
Also worth noting but 3pool is starting to deviate quite a bit from $1.00 due to the UST bank run (it accrues swap fees in the 3pool) we're going to need to account for this in our core contracts 😰 https://www.coingecko.com/en/coins/lp-3pool-curve

**Comment by sergfeldman** [comment]
Figure out the design and suggest an effective approach 
Possibly, the UI requires refactoring

**Comment by sergfeldman** [comment]
The decision: to show 
- TWAP price directly on the page
- Spot Price in a tooltip (question mark)

**Comment by 0xautohub** [comment]
Hey @sergfeldman I would like to select this one

**Comment by sergfeldman** [comment]
@sunny0714 You are assigned on this bounty

**Comment by 0xautohub** [comment]
Cool, thanks @sergfeldman

**Comment by 0xautohub** [comment]
Hey @sergfeldman this is just finished on this PR, Please check this out
https://github.com/ubiquity/ubiquity-dollar/pull/222

**Comment by sunny0714** [comment]
#222 linking PR

**Comment by sergfeldman** [comment]
@pavlovcik Please clarify if this issue can be closed as done.
