### ISSUE TITLE
Rename "Liquidity Mining" to "Staking"

### ISSUE THREAD

**Issue by littleflute23** [ubiquity/uad-ui#162]
<img width="154" alt="2022-05-12 20_49_01-Dashboard _ Ubiquity Dollar"
 src="https://user-images.githubusercontent.com/99516437/168192094-1d763a36-175a-4ff9-aa59-6abb6424dd28.png">

**Comment by sergfeldman** [comment]
Done in the pull request, waiting for the merge to the Master.
