### ISSUE TITLE
Change "Staking" (Previously Liquidity Mining) Interface.

### ISSUE THREAD

**Issue by littleflute23** [ubiquity/uad-ui#163]
<img width="511" alt="2022-05-12 21_15_43-Dashboard _ Ubiquity Dollar" src="https://user-images.githubusercontent.com/99516437/168192248-8f221d54-d903-44d7-89f8-47c2636e8def.png">

On the title that says "Liquidity Mining," I suggest changing that term into something like "Stake uAD-3CRV tokens-> Receive uBQ" or something of the sort.

**Comment by sergfeldman** [comment]
New title 
Stake uAD-3CRV tokens -> Receive uBQ

**Comment by sergfeldman** [comment]
Done in the pull request, waiting for the merge to the Master.
