### ISSUE TITLE
Change "Bonding Contract" Contract name to "Staking"

### ISSUE THREAD

**Issue by littleflute23** [ubiquity/uad-ui#164]
<img width="538" alt="2022-05-12 21_20_13-Telegram (480019)" src="https://user-images.githubusercontent.com/99516437/168192566-e5feef7d-36f9-4a1d-b7a2-219182943275.png">

**Comment by sergfeldman** [comment]
Bounty for community:
Minimum 50 USDC
Bonus 50 USDC 
The Bonus will be paid if the task is solved flawlessly https://github.com/ubiquity/ubiquity-dollar-development/discussions/184#discussioncomment-2950602

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by DevSCNinja** [comment]
Hey @sergfeldman, are you ready to assign this issue to me?

**Comment by sergfeldman** [comment]
@pavlovcik Please check that this issue has not been solved before.

**Comment by 0x4007** [comment]
> @pavlovcik Please check that this issue has not been solved before.

Looks like I solved it already - sorry for missing closing this issue.

<img width="870" alt="Screen Shot 2022-10-17 at 17 21 39" src="https://user-images.githubusercontent.com/4975670/196140746-330c0b12-6d21-4162-87a4-84929b0a6bc9.png">
