### ISSUE TITLE
"Add Liquidity" UI for Easier UBQ Farming

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#167]
In order to make it easier for people to start farming UBQ, we should take the UI from [crv.to](https://crv.to/pool) to allow people to deposit their stablecoins into the Curve metapool.

![photo_2022-05-13 09 38 47](https://user-images.githubusercontent.com/4975670/168194209-a3e89c0e-bde1-4676-92d8-8fc01617b355.jpeg)

**Comment by sergfeldman** [comment]
zashton, [6/15/2022 7:58 PM]
[ File : ubqdao_curve.zip ]
source code
[ubqdao_curve.zip](https://github.com/ubiquity/ubiquity-dollar-development/files/8912511/ubqdao_curve.zip)

zashton, [6/15/2022 8:02 PM]
[ File : utils.js ]
the main contract calls to do all the add/withdraw/estimate are in utils
[utils.zip](https://github.com/ubiquity/ubiquity-dollar-development/files/8912515/utils.zip)

zashton, [6/15/2022 8:03 PM]
the FE framework used is https://vuetifyjs.com/

zashton, [6/15/2022 8:05 PM]
the ABIs & contract addresses are in config, since you guys are using the old metapools , you should use curveFactoryV2Address curveFactoryV2ABI

zashton, [6/15/2022 8:07 PM]
some apis from curve that you can use 
https://api.curve.fi/api/getFactoryPools
https://api.curve.fi/api/getFactoryAPYs
these are for the old metapools

**Comment by 0x4007** [comment]
So I just remembered we have supporting smart contract infrastructure for this so the primary focus could be integrating this smart contract with the UI instead of merging zashton's UI code into ours. I think there are probably useful codebits from his UI to copy/paste in.

https://etherscan.io/address/0x8ec066d75d665616a94f2eccdbe49b54eaeefc78#code

https://github.com/ubiquity/ubiquity-instadapp/blob/master/backend/contracts/mainnet/connectors/ubiquity/main.sol

**Comment by 0xautohub** [comment]
Hey @pavlovcik @sergfeldman I'm interested in this issue
I think that this is a great starter for me to get accustomed to the overall project
Hope you guys to assign this issue to me

**Comment by sergfeldman** [comment]
Hey @sunny0714 thank you for your interest.
This particular issue has at least 2 ways of implementation mentioned in the comments above.
We will discuss this next week and let you know the way we prefer. 
Until then, please do not start solving this issue.

**Comment by 0xautohub** [comment]
@sergfeldman yeah, got it

**Comment by devmaster54** [comment]
@sergfeldman Can I work on this bounty?

**Comment by super-dev0728** [comment]
Hello. Can I start work for this issue?

**Comment by sergfeldman** [comment]
@super-dev0728 Please, don't take this bounty. 
The new portion of bounties will be available in the near future.

**Comment by sergfeldman** [comment]
> So I just remembered we have supporting smart contract infrastructure for this so the primary focus could be integrating this smart contract with the UI instead of merging zashton's UI code into ours. I think there are probably useful codebits from his UI to copy/paste in.
> 
> https://etherscan.io/address/0x8ec066d75d665616a94f2eccdbe49b54eaeefc78#code
> 
> https://github.com/ubiquity/ubiquity-instadapp/blob/master/backend/contracts/mainnet/connectors/ubiquity/main.sol


The bounty should be implemented according to this info ^
The bounty can be taken.

**Comment by 0x4007** [comment]
> The bounty should be implemented according to this info ^

Yes, so just to clarify: the original idea was to simply take the deposit liquidity UI code from Zashton. After acquiring the code from him, I realized that we have existing smart contract logic that helps with exactly this issue. The best product from the user's perspective is one that automates the intermediary steps of handling the LP token. 

We should allow the user to deposit any (USDC/USDT/DAI/uAD) stablecoin and immediately start farming UBQ. This logic is handled primarily by the `apeIn` method in the linked Solidity code.

@sergfeldman because this task touches both UI and Solidity code, I think we should consider increasing the bounty. I think a lot of the logic can be taken directly from the Solidity and React code, but time must be spent to piece it together. I think $500 bounty might be more appropriate.

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by 0x4007** [comment]
I think this bounty should be remade to build a UI for ubiquity/ubiquity-dollar#301 

new bounty is here 

https://github.com/ubiquity/uusd.ubq.fi/issues/5
