### ISSUE TITLE
Change "10.10% - 19.65%APY" to "Projected APY ..." instead.

### ISSUE THREAD

**Issue by littleflute23** [ubiquity/uad-ui#168]
<img width="566" alt="2022-05-12 22_01_40-Dashboard _ Ubiquity Dollar" src="https://user-images.githubusercontent.com/99516437/168196603-271aeb5d-63cf-4cc4-8fe3-c727fea624a1.png">

Sort of like Ribbon Finance
<img width="223" alt="2022-05-12 21_23_36-Ribbon Finance_ Decentralised Crypto Structured Products" src="https://user-images.githubusercontent.com/99516437/168199116-9c24eb92-6775-44ec-b5d8-3438c89ea25b.png">

**Comment by littleflute23** [comment]
Is there a reason why you can't include the Max APY in the original USDC APY button?

**Comment by littleflute23** [comment]
Also the 10% fee should not be highlighted.

**Comment by sergfeldman** [comment]
The requirements should be clarified. 

Projected APY ... 

where ... is max APY?

**Comment by sergfeldman** [comment]
If so, the new title will look like 
Projected APY 19.65%
