### ISSUE TITLE
Rename "Swap Tokens" to just "Swap"

### ISSUE THREAD

**Issue by littleflute23** [ubiquity/uad-ui#169]
<img width="151" alt="2022-05-12 22_22_11-Dashboard _ Ubiquity Dollar" src="https://user-images.githubusercontent.com/99516437/168198783-e4fed456-a085-492f-bcb3-bf05c79e83a7.png">

**Comment by sergfeldman** [comment]
Done, plan to create the pull request to Master AFTER the UI repo refactoring is merged to Master
