### ISSUE TITLE
Add a URI Setter method to the Stake (Bond) NFT Contract

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#170]
The implementation is messed up on the NFT token contract and it does not display any metadata on OpenSea or Etherscan. We should include the deposit details and give it a graphic!

https://opensea.io/collection/unidentified-contract-ri6rdz48y4

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by pwilson77** [comment]
Hi I could take a look at this

**Comment by 0x4007** [comment]
> Hi I could take a look at this

Sounds good. You're authorized to proceed.

**Comment by pwilson77** [comment]
Hi I have got some questions
1. Can I get the name of the NFT smart contract
2. Also the address NFT contract on etherscan

**Comment by sergfeldman** [comment]
@pwilson77 Hi, please review the documentation
https://github.com/ubiquity/ubiquity-dollar/wiki/18.-Smart-Contracts

**Comment by pwilson77** [comment]
Found it thanks, I believe its ERC1155Ubiquity.sol right?

**Comment by sergfeldman** [comment]
> Found it thanks, I believe its ERC1155Ubiquity.sol right?

@pavlovcik Please, check whether this is a right smart contract for this issue

**Comment by 0x4007** [comment]
I linked the OpenSea page because it shows the contract there.

https://etherscan.io/address/0x2da07859613c14f6f05c97efe37b9b4f212b5ef5#code
https://github.com/ubiquity/uad-contracts/blob/main/contracts/BondingShareV2.sol

**Comment by pwilson77** [comment]
oh ok my bad I couldn't find it on the page that's why I asked

**Comment by bluecryptodev** [comment]
Hi, @pavlovcik .
Did you set your token uri as json string?
For example like this?
"{
"name": "Bonding Share",
"description": "Ubiquity Bonding Share V2",
"image": "https://bafybeifibz4fhk4yag5reupmgh5cdbm2oladke4zfd7ldyw7avgipocpmy.ipfs.infura-ipfs.io/"
}"

**Comment by 0x4007** [comment]
> Hi, @pavlovcik . Did you set your token uri as json string? For example like this? "{ "name": "Bonding Share", "description": "Ubiquity Bonding Share V2", "image": "https://bafybeifibz4fhk4yag5reupmgh5cdbm2oladke4zfd7ldyw7avgipocpmy.ipfs.infura-ipfs.io/" }"

I suggest checking the read contract interface on the smart contract before blocking yourself waiting for a response to this. Looks like the image URL is broken! Perhaps its wise to add a setter to this contract so that we can avoid a redeploy in the future. I think lets convert the bounty to reflect this. 

- [ ] Add a setter to update this in the future in case this type of issue happens again. 
- [ ] Write a test for this setter.
- [ ] Also it would be great to verify that the new contract works by deploying on a test network that OpenSea supports.

---

<img width="673" alt="Screenshot 2022-12-09 at 03 37 05" src="https://user-images.githubusercontent.com/4975670/206551064-d45efd52-d00c-4ad3-a004-b4ffa5f45903.png">

https://bafybeifibz4fhk4yag5reupmgh5cdbm2oladke4zfd7ldyw7avgipocpmy.ipfs.dweb.link/

<img width="612" alt="image" src="https://user-images.githubusercontent.com/4975670/206551141-cc2ed1b9-71cd-4398-b0fe-dac8e1a4d797.png">

**Comment by zorglob21** [comment]
> I suggest checking the read contract interface on the smart contract before blocking yourself waiting for a response to this. Looks like the image URL is broken! Perhaps its wise to add a setter to this contract so that we can avoid a redeploy in the future. I think lets convert the bounty to reflect this.
> 
>     * [ ]  Add a setter to update this in the future in case this type of issue happens again.
> 
>     * [ ]  Write a test for this setter.
> 
>     * [ ]  Also it would be great to verify that the new contract works by deploying on a test network that OpenSea supports.

Hello, to be precise : do you want a setter to specifically set the image url value or whole URI from BondingShareV2.sol, and regarding testing the contract, do you mean specifically this function only?
Thanks

**Comment by 0x4007** [comment]
> > I suggest checking the read contract interface on the smart contract before blocking yourself waiting for a response to this. Looks like the image URL is broken! Perhaps its wise to add a setter to this contract so that we can avoid a redeploy in the future. I think lets convert the bounty to reflect this.
> > ```
> > * [ ]  Add a setter to update this in the future in case this type of issue happens again.
> > 
> > * [ ]  Write a test for this setter.
> > 
> > * [ ]  Also it would be great to verify that the new contract works by deploying on a test network that OpenSea supports.
> > ```
> 
> Hello, to be precise : do you want a setter to specifically set the image url value or whole URI from BondingShareV2.sol, and regarding testing the contract, do you mean specifically this function only? Thanks

Whatever offers us the most flexibility in the future makes the most sense. So I believe that means to be able to set the entire JSON object.

**Comment by zorglob21** [comment]
Hello @pavlovcik ,
I would like to work on this task. Could you be more precise about the required tests and type of access control?(i have seen there are onlyMinter for example)
I think i will need to modify the erc1155 code to achieve this, is this ok with your project?
 You should then be able to modify the whole URI variable.

**Comment by sergfeldman** [comment]
> Hello @pavlovcik , I would like to work on this task. Could you be more precise about the required tests and type of access control?(i have seen there are onlyMinter for example) I think i will need to modify the erc1155 code to achieve this, is this ok with your project? You should then be able to modify the whole URI variable.

@zorglob21 Hello, thanks for the request.
Please wait for a response as @pavlovcik is currently busy with a conference.

**Comment by 0x4007** [comment]
> I think i will need to modify the erc1155 code to achieve this, is this ok with your project?
> You should then be able to modify the whole URI variable.

That sounds good.

The tests just need to verify that the setter functions as expected. We're looking to have full code coverage in the tests. You could take a look at our UbiquiStick tests to find some inspiration.

**Comment by zorglob21** [comment]
@pavlovcik great, i'll start now.

**Comment by zorglob21** [comment]
i am sorry to ask this but i'm new to this project and confused about a few things :
The contract BondingSharev2 isn't present in the main github repository : https://github.com/ubiquity/ubiquity-dollar but is only present there : https://github.com/ubiquity/uad-contracts.
Which repository should be cloned, and in what sol. file should i write the function should this task be assigned to me?

**Comment by 0x4007** [comment]
> i am sorry to ask this but i'm new to this project and confused about a few things : The contract BondingSharev2 isn't present in the main github repository : https://github.com/ubiquity/ubiquity-dollar but is only present there : https://github.com/ubiquity/uad-contracts. Which repository should be cloned, and in what sol. file should i write the function should this task be assigned to me?

Sorry that is our fault! We just started renaming the smart contracts last week. 

Please look at this https://github.com/ubiquity/ubiquity-dollar/issues/292#issuecomment-1288255782 to have more clarity on the renames.

**Comment by zorglob21** [comment]
okay, so i would like to get this issue assigned to me.
I will use the STAKING_MANAGER_ROLE as access control for the uri setter

**Comment by 0x4007** [comment]
I'm personally not super familiar with the access control manager roles but that sounds correct.

**Comment by 0x4007** [comment]
Thanks for the heads up in the group chat to assign you @zorglob21

**Comment by zorglob21** [comment]
@pavlovcik my pr is ready but i had to modify the ERC1155.sol script from open zeppelin library in the lib folder, however i'm uncertain on how to push this commit the sub module folder.
![Screenshot 2022-12-21 101600](https://user-images.githubusercontent.com/22262445/208869436-b2e00581-286c-47c9-a178-f555a33c9c48.jpg)

**Comment by 0x4007** [comment]
I didn't test this but I want to move things along faster with all these open PRs. @0xcodercrane please test and @sergfeldman please follow up about this.

@zorglob21 please write your payment address here. Thanks!

**Comment by zorglob21** [comment]
here is my address : 0xDFFfAD1a8302Cb9573991ab998A85174602DD2F9

@pavlovcik  I did test this on testnet (only the stakingShare contract and the required dollarManager were deployed).
I also deployed the previous version where i modified the file directly in the openzeppelin sub module and made a succesful transaction on goerli here :[https://goerli.etherscan.io/tx/0x6eb9d7b8b6d2252f3279dfa15c31ca84cf30e598e8bbdf5d416da7b326935e2d](url)

**Comment by 0x4007** [comment]
https://etherscan.io/tx/0x1dacd2c7bdaff667daec6f67da2a396aee7b5ee4cdb7dcb8568a207cc7a92d2c
https://etherscan.io/tx/0x8c7a1ec84b75fa6017a5fd007de1cdf8e1a25f279f15b40f0e81205c5f68c55c
