### ISSUE TITLE
Research setup of the backend for Staging

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/uad-ui#174]
**Background**

The goal is to have a fully functional Staging environment.
It will allow performing testing by each team member without installations in the local environment.

It must be possible to perform all the actions with all the products.

For Bonds
- Get to know the products
- Buy/create
- Check
- Sell/withdraw
- Bond
- Collect tokens from the Bond vesting period
- Swap

The frontend of the Staging environment is already established at 
https://ubiquity-dollar-staging.vercel.app/

There is a list of cloud services focused on deploying nodes
https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/
Some of them provide a free tier 
https://www.alchemy.com/pricing 

There is a list of Ethereum Testnets
https://ethereum.org/en/developers/docs/networks/

Some services provide API to Ethereum nets
https://www.quicknode.com/chains/eth 

**To do** 

Research setup of the backend for Staging

Explore hypotheses one by one starting from the top:
1. To deploy own node on a cloud service 
2. To deploy own contracts on Ethereum test nets 
3. To use API to Ethereum nets
4. Explore other options 

The result of the research must have a clear vision of how to set up  the backend for Staging 
After that, the backend will be connected to the Staging frontend.

**Comment by 0x4007** [comment]
It's faster to write instructions on how to setup a local environment for testing than to build a system on a remote VPS. I like the idea but from a strictly profitability standpoint I voted that the impact is small.

**Comment by sergfeldman** [comment]
VPS on Digital Ocean is the preferable option

**Comment by sergfeldman** [comment]
Explore the access to the Staging for UbiquityStick NFT

**Comment by sergfeldman** [comment]
Please, provide the access to Digital Ocean dashboard to Alex

**Comment by 0x4007** [comment]
Still need to make a UI for this and expose the Hardhat RPC over the API (should be pretty quick to do) but still seeking to host the hardhat blockchain on some other service like GitHub Actions because its pretty expensive to run currently

**Comment by sergfeldman** [comment]
The suggestion is to explore option to run the node on/with help of the Github actions
