### ISSUE TITLE
Launch Party - Resolve Gelato to Arrakis renaming

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#175]
As mentioned by Alex, Gelato was renamed to Arrakis https://www.arrakis.finance/, so we need to update the links; and the links to the pool specifically, otherwise people won't be able to buy LP tokens.

- Update links
- Make sure pools are accessible

**Comment by 0x4007** [comment]
https://github.com/ubiquity/ubiquity-dollar-development/issues/177 would make this issue obsolete

**Comment by Zequez** [comment]
Alright closing this one since we're gonna do #177
