### ISSUE TITLE
Continuous Deployment via fleek.co (instead of Vercel)

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#187]
[fleek.co](https://fleek.co) seems to support continuous deployment like Vercel BUT you can link an organization account for free!

In case I don't have time to solve this immediately, I would love for somebody else like @Zequez to take a crack at it. My builds don't seem to work.

![Screen Shot 2022-06-09 at 04 38 32](https://user-images.githubusercontent.com/4975670/172712751-a824beed-aa54-4c4a-920c-077d86df2539.png)

**Comment by sergfeldman** [comment]
GitHub organization + Fleek Basic FOR PERSONAL ACCOUNTS https://fleek.co/pricing/

**Comment by sergfeldman** [comment]
Start from the development repo

**Comment by 0x4007** [comment]
# Compiling using GitHub Actions

I really like @zapaz implementation where they handle compiling using GitHub Actions. The GitHub Ubuntu runner has enough power to handle our job. The best part is that its free!

- 2-core CPU
- 7 GB of RAM memory
- 14 GB of SSD disk space

[source](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).

<img width="645" alt="image" src="https://user-images.githubusercontent.com/4975670/176285227-9c64832d-8f21-4f4c-abbe-b0e8c940040e.png">

https://github.com/Kredeum/kredeum/blob/beta/.github/workflows/dapp-build.yml

**Comment by sergfeldman** [comment]
Bounty for community:
Minimum 400 USDC
Bonus 200 USDC 
The Bonus will be paid if the task is solved flawlessly https://github.com/ubiquity/ubiquity-dollar-development/discussions/184#discussioncomment-2950602

**Comment by zapaz** [comment]
done here #204   

deployments of main branch available on https://dev.ubq.fi

PR previews also available on specific urls

**Comment by 0x4007** [comment]
Feel free to close the issues in the future @zapaz !
