### ISSUE TITLE
Add WalletConnect Support

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#19]
@Zequez this is a luxury and can be put on the backlog, but I could never figure out the interface the other wallets use (window.web3 ?) 

This is opera touch on iOS and it doesn't work. Would be awesome if we could add support :)

![image](https://user-images.githubusercontent.com/4975670/135542141-efc6cdda-0748-4dce-b480-51141959c22e.png)

**Comment by myallcodebase** [comment]
https://walletconnect.com/

**Comment by sergfeldman** [comment]
Bounty for community:
Minimum 100 USDC
Bonus 50 USDC 
The Bonus will be paid if the task is solved flawlessly https://github.com/ubiquity/ubiquity-dollar-development/discussions/184#discussioncomment-2950602

**Comment by sergfeldman** [comment]
Assigned to @kecrypto

**Comment by sergfeldman** [comment]
This task has not been completed within an acceptable time frame.

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by 0x4007** [comment]
I updated the bounty because after @kecrypto attempted it and didn't complete it, I looked into it myself and realized that Zequez probably didn't check the wallet state to load all the views in a Wallet Connect compliant way?

This will require a restructuring of all the view state management system as well in order to work with MetaMask and WalletConnect.

**Comment by 3commascapital** [comment]
i can take a look at this next

**Comment by 0x4007** [comment]
> i can take a look at this next

That would be lovely! I think its up your alley as it requires a lot of digging through React code.

**Comment by 3commascapital** [comment]
i am not able to trigger the alert (perhaps it was taken out of the codebase) but i was able to trigger the condition of being unable to connect while in opera desktop. on mobile the page simply crashes. i will look into this next

**Comment by 0x4007** [comment]
> i am not able to trigger the alert (perhaps it was taken out of the codebase) but i was able to trigger the condition of being unable to connect while in opera desktop. on mobile the page simply crashes. i will look into this next

Just to clarify (and I just renamed the issue to emphasize this) the main task is to enable WalletConnect v2 support. v1 and v2 [are incompatible](https://twitter.com/walletconnect/status/1402611222873313283?lang=en) so its prudent of us to future proof our UI during its active development phase.

If you could leave "injected provider" aka MetaMask in that would be ideal as well.

**Comment by greg-schrammel** [comment]
hey, it is recommended to wait for more wallets to support WalletConnect v2 before using it in dapps, after wallets have been integrated, the dapp migration should as easy as upgrating a package. 

this is kind of a solved issue in the ecosystem with packages like [wagmi](https://wagmi.sh), I can integrate it if you wish, replacing your proprietary solution

I'd also recommend using [react-query](https://tanstack.com/query/v4) to manage async state, like token balances, allowances, etc.

**Comment by 0x4007** [comment]
> hey, it is recommended to wait for more wallets to support WalletConnect v2 before using it in dapps, after wallets have been integrated, the dapp migration should as easy as upgrating a package.

Assuming that WalletConnect follows the [semver standard](https://semver.org/), by definition, the WalletConnect v2 upgrade should not be "as easy as upgrading the package."

It makes a lot more sense for us to handle the "major change" upgrade as part of this bounty asap, and then expect to upgrade the package for "minor" updates or "patch" updates to support the other wallets.

> I'd also recommend using [react-query](https://tanstack.com/query/v4) to manage async state, like token balances, allowances, etc.

I can not speak from a place of wisdom as I have never used react-query, however, I am against introducing new frameworks/dependencies unless its absolutely necessary. This is to lighten our techstack and the reduce the friction of onboarding new developers (extremely relevant due to our bounty program.)

**Comment by greg-schrammel** [comment]
the [official wallet connect web3Modal](https://docs.walletconnect.com/2.0/web3modal/react/installation) recommends using wagmi, you'd rather use the [standalone version](https://docs.walletconnect.com/2.0/web3modal/standalone/installation)?

**Comment by 0x4007** [comment]
I have never used wagmi so I'm not sure. Generally speaking I would stick with the leaner option, so that means standalone. I'm asking some of the other veteran Ubiquity Dollar contributors their opinions on Telegram now.

**Comment by 0x4007** [comment]
@zgorizzo69 says use wagmi so lets do that.

**Comment by 0x4007** [comment]
@greg-schrammel looks like your PR solves the bounty. Thanks so much! Can you share your DAI/UBQ address here?

**Comment by 0x4007** [comment]
Will close when paid.

**Comment by greg-schrammel** [comment]
uhu, my address is `0x507F0daA42b215273B8a063B092ff3b6d27767aF`

**Comment by 0x4007** [comment]
> uhu, my address is `0x507F0daA42b215273B8a063B092ff3b6d27767aF`

https://etherscan.io/tx/0x5fae6f7954a13f90fb8c856804b1e07a2521144efe7207d1f9fad6be49355df1
https://etherscan.io/tx/0x7b5784de043780856088d06971d0c27bc586efc438d74dedc2c6b7d4dfc15a36
