### ISSUE TITLE
Implement Beta-testing mode

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/uad-ui#193]
Implement Beta-testing mode

If 
1) The user has an UbiquiStick NFT 
And 
2) Ubiquity Hardhat RPC endpoint is available 

Then 
- A modal pops up that allows connecting the wallet to Ubiquity Hardhat RPC endpoint 
And
- Simple authentication (nice to have, the research is needed) 

Else
- Show an error

**Comment by Zequez** [comment]
I'm not sure if I remember correctly, but I recall we talked about abandoning the RPC-endpoint approach for detailed instructions as to how to setup the local environment for testing.

I would like to propose a new possibility to this: we can make an executable script that takes care of installing all the necessary dependencies and running al the necessary commands, and has a simplified GUI that allows anyone to run and control the local environment.

We could take the following steps:
- Write the precise instructions, to run the local environment (all needed software, Git, Node, Yarn, etc)
- Identify what changes we would need for the codebase to be strictly GUI-controlled (in a way we don't need people to make manual changes to files on a code editor or filesystem)
- Write a cross-platform CLI script that can install the entire thing with simple prompts and controls
- Add a simple GUI on top of the script using a webview. [We could try out Tauri.](https://tauri.app/) for this.

This way we don't have to rely on running a node and it would encourage us to enhance the development/testing experience itself. We can add additional features to the GUI such as advancing new blocks, faucet existing accounts, resetting the node, changing the fork block height, seeing the list of loaded contracts, etc.

@pavlovcik would you be onboard to this approach?

**Comment by 0x4007** [comment]
There's a lot to address here but I don't imagine that the marketing folks would be keen on learning how to interact with a shell (command line) @firstimecoding @littleflute23 @Niamie @ChefYaboyardi @elSepatura 

The VPS hosted instance already works. I just have it disabled because of the high fees involved to run a VPS with the power to compile the smart contacts and host the UI. This level of power can be accommodated for free by the GitHub runners though. 

I propose that the next/final(?) step to make Sergey's vision work is to have GitHub actions compile (and then host the compiled files) and a weaker VPS can run the hardhat instance without having to compile.

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by 0x4007** [comment]
How about connecting to Tenderly forks via an RPC? That could be very useful in a pinch


![image](https://user-images.githubusercontent.com/4975670/196698092-24428762-3ba2-48f9-a25e-d9f4782d451f.png)

**Comment by sergfeldman** [comment]
Note for a bounty hunter:
When you apply to this issue, please suggest a list of smaller issues to divide this issue into.

**Comment by 0x4007** [comment]
This is actually a more vague specification (a duplicate) of https://github.com/ubiquity/ubiquity-dollar/issues/209

This also includes UbiquiStick NFT as a requirement to beta test, but this could be burdensome for our devpool participants. I think we should solve the burden issue before gating the beta testing tools with the UbiquiStick unfortunately. 

We can continue that conversation either here, or create a new GitHub Discussion.
