### ISSUE TITLE
Convert Project From Hardhat to Foundry

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#206]
More details on this later but it appears that the advanced developer sentiment in the ecosystem is leaning heavily towards Foundry being the future for development and writing tests.

Because one of the killer features of Foundry is that automated tests for the smart contracts are written also in Solidity, this means that the bounty hunter must port all of our tests over from TypeScript to Solidity!

Also the deployment scripts I believe need to be recreated.

**Comment by george-shammar** [comment]
Would like to take a crack at this. GGR

**Comment by sergfeldman** [comment]
@george-shammar There are no technical details on this issue at the moment. 
In this case, it will be necessary to discuss the requirements, which will take your time.

Are you ready to spend time within the specified budget not only on development but also on clarifying technical requirements?

**Comment by 0x4007** [comment]
Maybe @zgorizzo69 has some thoughts on this because we had a discussion around using Foundry

**Comment by 0xautohub** [comment]
@sergfeldman , @pavlovcik  I have just applied as a frontend dev role from the link on discord.. and I found that there is a request for participating on bounty.. hope to get involved in this issue
Could anyone share the link of hardhat project? I would like to estimate how much work it would be
Thanks

**Comment by 0x4007** [comment]
> @sergfeldman , @pavlovcik I have just applied as a frontend dev role from the link on discord.. and I found that there is a request for participating on bounty.. hope to get involved in this issue Could anyone share the link of hardhat project? I would like to estimate how much work it would be Thanks

Its this repo kek

**Comment by 0xautohub** [comment]
🤣🤣🤣 
I did'nt find any hardhat config file in the root directory.. so thought that there is another link
Thanks 🤝

**Comment by Zequez** [comment]
That looks cool; supposedly much faster than Hardhat! And it could be GUI-ed with Tauri since Tauri has a Rust backend! It looks promising.

It's a good opportunity to consolidate all the smart contracts development into a single tool configuration.

**Comment by george-shammar** [comment]
@pavlovcik and @sergfeldman Kindly let me know when it's a good time to get started on this. Regards.

**Comment by 0x4007** [comment]
@george-shammar I've never actually used Foundry before and wanted to know, how will we run our Hardhat tasks? Do they also need to be converted?

**Comment by george-shammar** [comment]
> @george-shammar I've never actually used Foundry before and wanted to know, how will we run our Hardhat tasks? Do they also need to be converted?

@pavlovcik It depends but Foundry could be integrated with Hardhat. You can check this out: https://book.getfoundry.sh/config/hardhat

**Comment by 0x4007** [comment]
It seems a lot cleaner to go full Foundry. Is this realistic? 

This way, future maintainers only need proficiency in Foundry to contribute (vs both)

**Comment by george-shammar** [comment]
> It seems a lot cleaner to go full Foundry. Is this realistic?
> 
> This way, future maintainers only need proficiency in Foundry to contribute (vs both)

I thought so too and that's why I said it depends. I assumed you wanted to retain your Hardhat tasks. But I'll advise going full-on Foundry.

**Comment by 0x4007** [comment]
# Specification

I did some research this afternoon and I believe this is the full scope of work - let me know if you think there might be anything missing.

1. CONFIG: The hardhat related files/dependencies should be removed.
2. TASKS: we only need to port the `priceReset` task we just finished (kek) https://github.com/ubiquity/ubiquity-dollar/pull/210 
3. DEPLOYMENT SCRIPTS: I assume that we need new deployment scripts so that our contracts will deploy on the local Foundry test blockchain?
4. TESTS: We never did any fuzzing so unfortunately we should have all of the tests ported to get that automatically.

## Bonus tasks in order of interest to port over

This is not mandatory as I do not see any immediate future needs for these, but porting these will allow you to learn more about the inner workings of our protocol.

1. `revoke.ts`
a. We have an access control manager (a whitelist) of addresses with minting and burning rights for our dollar. This is a script to revoke minter/burner permissions from an address (remove from the whitelist, basically.) I suppose we don't have a `grant` task (the opposite of revoke) because those rights presumably were set in the deployment scripts.
2. `incentive.ts`
a. Our protocol has the capability to inject arbitrary logic on top of any DEX market for swaps. Basically, from the perspective of our dollar's token smart contract, we associate transfers to the contract address of any DEX. If a transfer is happening to or from that address, we invoke custom additional logic mid transfer. This allows us more flexibility to add stabilization strategies during a swap, for example.
3. `manager.ts`
a. We have a central protocol manager contract that keeps track of all the proxy contracts. This just displays all of the proxy contracts and their addresses.

**Comment by 0x4007** [comment]
> # Specification
> I did some research this afternoon and I believe this is the full scope of work - let me know if you think there might be anything missing.
> 
> 1. CONFIG: The hardhat related files/dependencies should be removed.
> 2. TASKS: we only need to port the `priceReset` task we just finished (kek) [complete a hardhat task to reset price #210](https://github.com/ubiquity/ubiquity-dollar/pull/210)
> 3. DEPLOYMENT SCRIPTS: I assume that we need new deployment scripts so that our contracts will deploy on the local Foundry test blockchain?
> 4. TESTS: We never did any fuzzing so unfortunately we should have all of the tests ported to get that automatically.
> 
> ## Bonus tasks in order of interest to port over
> This is not mandatory as I do not see any immediate future needs for these, but porting these will allow you to learn more about the inner workings of our protocol.
> 
> 1. `revoke.ts`
>    a. We have an access control manager (a whitelist) of addresses with minting and burning rights for our dollar. This is a script to revoke minter/burner permissions from an address (remove from the whitelist, basically.) I suppose we don't have a `grant` task (the opposite of revoke) because those rights presumably were set in the deployment scripts.
> 2. `incentive.ts`
>    a. Our protocol has the capability to inject arbitrary logic on top of any DEX market for swaps. Basically, from the perspective of our dollar's token smart contract, we associate transfers to the contract address of any DEX. If a transfer is happening to or from that address, we invoke custom additional logic mid transfer. This allows us more flexibility to add stabilization strategies during a swap, for example.
> 3. `manager.ts`
>    a. We have a central protocol manager contract that keeps track of all the proxy contracts. This just displays all of the proxy contracts and their addresses.

@george-shammar you are authorized to proceed. Good luck 🫡

**Comment by george-shammar** [comment]
> > # Specification
> > I did some research this afternoon and I believe this is the full scope of work - let me know if you think there might be anything missing.
> > 
> > 1. CONFIG: The hardhat related files/dependencies should be removed.
> > 2. TASKS: we only need to port the `priceReset` task we just finished (kek) [complete a hardhat task to reset price #210](https://github.com/ubiquity/ubiquity-dollar/pull/210)
> > 3. DEPLOYMENT SCRIPTS: I assume that we need new deployment scripts so that our contracts will deploy on the local Foundry test blockchain?
> > 4. TESTS: We never did any fuzzing so unfortunately we should have all of the tests ported to get that automatically.
> > 
> > ## Bonus tasks in order of interest to port over
> > This is not mandatory as I do not see any immediate future needs for these, but porting these will allow you to learn more about the inner workings of our protocol.
> > 
> > 1. `revoke.ts`
> >    a. We have an access control manager (a whitelist) of addresses with minting and burning rights for our dollar. This is a script to revoke minter/burner permissions from an address (remove from the whitelist, basically.) I suppose we don't have a `grant` task (the opposite of revoke) because those rights presumably were set in the deployment scripts.
> > 2. `incentive.ts`
> >    a. Our protocol has the capability to inject arbitrary logic on top of any DEX market for swaps. Basically, from the perspective of our dollar's token smart contract, we associate transfers to the contract address of any DEX. If a transfer is happening to or from that address, we invoke custom additional logic mid transfer. This allows us more flexibility to add stabilization strategies during a swap, for example.
> > 3. `manager.ts`
> >    a. We have a central protocol manager contract that keeps track of all the proxy contracts. This just displays all of the proxy contracts and their addresses.
> 
> @george-shammar you are authorized to proceed. Good luck 🫡

Acknowledged.

**Comment by nshmadhani** [comment]
Hey, is this bounty still being worked on @george-shammar @pavlovcik ?

**Comment by george-shammar** [comment]
> Hey, is this bounty still being worked on @george-shammar @pavlovcik ?

Yes, it is.

**Comment by george-shammar** [comment]
@pavlovcik @sergfeldman I would like to release this bounty back into the pool. I may not be able to complete it within a reasonable time due to recent demands on my time from other engagements. It would be unfair to keep holding up the project when there may be others who can complete it ASAP. I had a brief chat with @pavlovcik in this regard. The project has been converted to Foundry. Contracts are able to deploy on the local foundry network- ANVIL. Deploy scripts have been re-written as well. The outstanding component is testing.

**Comment by 0x4007** [comment]
Formatting built in pretty cool https://twitter.com/gakonst/status/1566627137502584832?s=21&t=pZz9M2pZFQebCVLtuUddNA

**Comment by cuddle-dev** [comment]
> Formatting built in pretty cool https://twitter.com/gakonst/status/1566627137502584832?s=21&t=pZz9M2pZFQebCVLtuUddNA

yeah. that would be really helpful for prettier.

**Comment by nshmadhani** [comment]
[pavlovcik](https://github.com/pavlovcik) what is the scope of this bounty?

**Comment by 0x4007** [comment]
> [pavlovcik](https://github.com/pavlovcik) what is the scope of this bounty?

@nshmadhani the scope is specified in the specification above. @0xcodercrane is almost done with the conversion.

**Comment by 0x4007** [comment]
@0xcodercrane can you post your DAI address here?

**Comment by cuddle-dev** [comment]
> @0xcodercrane can you post your DAI address here?

0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46

**Comment by 0x4007** [comment]
> > @0xcodercrane can you post your DAI address here?
> 
> 0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46

https://etherscan.io/tx/0x12ff5dab4c27bfd23a27b776910e13f04677e57fbc0dfeeecf78978e241b26b6 🙌

**Comment by 0x4007** [comment]
https://github.com/transmissions11/foundry-template please take a look at this repo to see if there's any other things we should include related to this now being a Foundry project @0xcodercrane 

I already saw a couple of useful bits like how they only do "intense fuzz testing" on pushes to main.
> https://github.com/transmissions11/foundry-template/blob/main/.github/workflows/tests.yml

Also in the vscode settings he set the Solidity formatter to Foundry's which seems smart.
