### ISSUE TITLE
General Refactorings

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#212]
Can you clean up the repository for all the junk (leftover/unused files/scripts) and reorganize directory structure to make things less of a mess for our new bounty hunters?

There's a ton of little things, and I figured it would be best to assign to you because it would take a long time to produce a real specification. I trust your judgement!

[refactor/general](https://github.com/ubiquity/ubiquity-dollar/tree/refactor/general)

**Comment by Zequez** [comment]
I'll gladly take the responsibility for this.

**Comment by 0x4007** [comment]
> I'll gladly take the responsibility for this.

Thank you ser. I want to give you a warning that I just realized https://github.com/ubiquity/ubiquity-dollar/issues/206 this may result in a massive project reorg so you should probably standby to do this after this is complete.

**Comment by 0x4007** [comment]
https://github.com/ubiquity/ubiquity-dollar/pull/244
