### ISSUE TITLE
Bonding Shares UI Miscalculation

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#213]
~95k LP locked in bonding contract according to the UI, but Etherscan reports ~51k (and a max total supply of ~54k)

<img width="385" alt="image" src="https://user-images.githubusercontent.com/4975670/180863967-57187755-2130-49d7-ba6f-22132d27ef9a.png">

<img width="794" alt="image" src="https://user-images.githubusercontent.com/4975670/180864058-ec835dda-8a64-4e55-b751-9dbdf1e5f02f.png">

https://etherscan.io/token/0x20955cb69ae1515962177d164dfc9522feef567e?a=0xc251ecd9f1bd5230823f9a0f99a44a87ddd4ca38

# Research Required

Need to diagnose if this is a UI bug or a smart contract bug.

**Comment by 0x4007** [comment]
I think this is actually due to us dipping into the funds as a loan leading up to the fundraising. We need to reimburse the LP tokens. I need to calculate the precise amounts.

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by DevSCNinja** [comment]
Hi @sergfeldman, are you ready to assign this issue to me?
