### ISSUE TITLE
Wrong Network Infinite UI Crash Loop

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#215]
There's an infinite crash loop for when Metamask is connected on the wrong network (seems like anything but Ethereum mainnet)

The whole page seems to hot reload and it bogs down the browser.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/4975670/180885853-b5c95148-592f-4755-abb6-d35fbe1a9114.png">

**Comment by officialsupport-ui** [comment]
Kindly get in touch to get your issue resolved

**Comment by 0x4007** [comment]
Sorry but this one isn't for bounties yet

> Kindly get in touch to get your issue resolved

**Comment by 0x4007** [comment]
In the latest code this now just crashes upon loading the dApp because it is an unhandled error (smart contracts not found on other chains outside of mainnet!) We have logic for catching and displaying generic errors (including missing smart contracts, specifically) so connecting this logic to the rest of the smart contracts should close the issue.

Basically, to test, just switch to Optimism and then see the page not load when you refresh. 

Success conditions will be to display this error using our existing modal logic. Basically, it should let the user know that they need to switch to Ethereum mainnet to use our dApp.

**Comment by 0x4007** [comment]
Current status as of [7d286bb](https://github.com/ubiquity/ubiquity-dollar/commit/7d286bb4517091bc1058d7fcdace953c350d273e) loads the UI fine on Optimism but does not alert the user that they are on the wrong network. 

If we can re-enable the generalized error catching logic that displays in a modal to the user what's happening, then we can close this issue.

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by 21CenturyTarzan** [comment]
Hi @sergfeldman. I can fix this issue.
Please assign this task to me.

**Comment by sergfeldman** [comment]
@21CenturyTarzan You are assigned on this issue.

**Comment by 21CenturyTarzan** [comment]
ok. I will start right now.

**Comment by 21CenturyTarzan** [comment]
Hi, I fixed the issue.
How can I submit the result?

**Comment by sergfeldman** [comment]
> Hi, I fixed the issue. How can I submit the result?

@21CenturyTarzan  Please, do a pull request with your fix

**Comment by 21CenturyTarzan** [comment]
Hi @sergfeldman. I did a pull request.

**Comment by sergfeldman** [comment]
@21CenturyTarzan Hi, we will review the pull request by the end of the week

**Comment by 21CenturyTarzan** [comment]
ok.

**Comment by 21CenturyTarzan** [comment]
Hi, @sergfeldman. I made a small update of the source. Now it will read the chainId by reading the .env file.

**Comment by cuddle-dev** [comment]
How's everything going on this pull request? @pavlovcik  @21CenturyTarzan 
Please make sure the issue is connected to pull request properly if its already started

**Comment by sergfeldman** [comment]
@21CenturyTarzan Since there is no answer from you, this issue is returned to the DevPool so other developers can complete it

**Comment by rndquu** [comment]
seems that this issue can be closed because recently merged `WalletConnect` doesn't allow switching to other networks from `mainnet`

<img width="1440" alt="Screenshot 2022-12-12 at 15 42 13" src="https://user-images.githubusercontent.com/119500907/207048150-fe327215-15d3-4b45-9332-1350e50c43b0.png">

**Comment by 0x4007** [comment]
Thanks for the notice @rndquu! If you can post your DAI wallet address here I'll send you a bonus for helping to clean up the issues.

**Comment by rndquu** [comment]
@pavlovcik 

wallet: 0x336C033842FA316d470e820c81b742e62A0765DC

**Comment by sergfeldman** [comment]
> @pavlovcik
> 
> wallet: 0x336C033842FA316d470e820c81b742e62A0765DC

@rndquu For USDC use the same wallet or a different one?

**Comment by rndquu** [comment]
> > @pavlovcik
> > wallet: 0x336C033842FA316d470e820c81b742e62A0765DC
> 
> @rndquu For USDC use the same wallet or a different one?

the same one

**Comment by sergfeldman** [comment]
@rndquu Thank you https://etherscan.io/tx/0xc7a94cdf86886fffd87c7e035532c7ddaa61e35125fc6b55ef57f5fd9218dbf5
