### ISSUE TITLE
Untrusted PR CI/CD

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#223]
Cloudflare and Fleek seem to only work sometimes. We need reliable CI/CD to run on every commit on untrusted PRs for our bounty hunters in order to expedite the review process. More details later but must high level requirements:
- [ ] Must host deployments
- [ ] Must build and report results

**Comment by zhyd1997** [comment]
@pavlovcik 

Could I take this one 👀 ?

**Comment by 0x4007** [comment]
> @pavlovcik
> 
> Could I take this one 👀 ?

Hey @zhyd1997, I actually made this for @0xcodercrane as we've been discussing it the last few days in the DMs but in case he doesn't get started soon for some reason I'll tag you in!

**Comment by zhyd1997** [comment]
@pavlovcik 

Okay, thanks let me know 😄

**Comment by cuddle-dev** [comment]
Thanks for waiting @pavlovcik . I was just thinking how to make this working without changing current CI/CD process. So my decision is basically like the following.

- [ ] Github action will check build, lint, unit tests (for only contracts right now) on every commit/ every pr into main branch.
- [ ] We will keep cloudflare continuous deployment script.
- [ ]  We need to think how to break down the products into staging and production later

**Comment by 0x4007** [comment]
> [ ] - Github action will check build, lint, unit tests (for only contracts right now) on every commit/ every pr into main branch. 

This should be on the UI code especially as well. The scripts are already done so you just need to call them from CI.

> [ ] - we will keep cloudflare continuous deployment script. [ ] - We need to think how to break down the products into staging and production later

dev/staging/production should be determined by the branch.

**Comment by cuddle-dev** [comment]
> dev/staging/production should be determined by the branch.

so bounty hunters will create a pr into dev? they don't have a permission to staging/production branch right?

**Comment by 0x4007** [comment]
> > dev/staging/production should be determined by the branch.
> 
> so bounty hunters will create a pr into dev? they don't have a permission to staging/production branch right?

"dev" should be, ideally, a unique link associated with each commit. Staging/production can be special protected branches

**Comment by cuddle-dev** [comment]
sounds reasonable
