### ISSUE TITLE
Inventory Link Broken With PR 12

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#24]
#12 broke the feature to click on an asset in your Ubiquity inventory to see the balance on etherscan.

![image](https://user-images.githubusercontent.com/4975670/135738736-fe04116b-1ae4-4ef1-91c2-754721d2188d.png)

![image](https://user-images.githubusercontent.com/4975670/135738747-008a4533-1833-4c3f-acb1-dc3bfef6f4af.png)
https://etherscan.io/error?e=5&t=undefined

**Comment by Zequez** [comment]
I'll just take care of this as part of https://github.com/pavlovcik/uad-ui/issues/29

**Comment by 0x4007** [comment]
Fixed in 599f69f
