### ISSUE TITLE
Enhanced type safety

### ISSUE THREAD

**Issue by cuddle-dev** [ubiquity/uad-ui#250]
### Problem

Regarding to workspace conversion, we replaced typechain types with a generic `ethers.Contract` which looks like not safe.

Refer the following link for more details
https://github.com/ubiquity/ubiquity-dollar/pull/249#discussion_r964612548

**Comment by sergfeldman** [comment]
@0xcodercrane Please, provide your time estimate so I can define a price for bounty hunters.

**Comment by cuddle-dev** [comment]
> @0xcodercrane Please, provide your time estimate so I can define a price for bounty hunters.

This is still ongoing because that existed when we were using hardhat. I will answer with the ETA once foundry conversion done. 
I think that would be better to keep this issue not started.

**Comment by 0x4007** [comment]
Bounty hunter be sure to check the comment for context.

**Comment by BeanieMen** [comment]
@0xcodercrane can you elaborate a little?
thanks

**Comment by BeanieMen** [comment]
i need some help with @/dollar-types, as to where is it now

**Comment by BeanieMen** [comment]
@pavlovcik i need some help with @/dollar-types

**Comment by BeanieMen** [comment]
uhh

**Comment by cuddle-dev** [comment]
Oops, the bounty has been delayed a lot. I don't get it what is your concern about @/dollar-types

**Comment by BeanieMen** [comment]
i assumed that you wanted to switch back to DebtCoupon

**Comment by BeanieMen** [comment]
> The custom typing DebtCoupon has been replaced with a generic Contract typing. @0xcodercrane and I had a discussion on this in Telegram and agreed that these should be fixed/switched back in the future for enhanced type safety. I understand that there were complications to get these custom typings stable with Foundry.

**Comment by 0x4007** [comment]
In case it is not clear, don't use the generic `ethers.Contract` type, use the custom generated types basically.

**Comment by molecula451** [comment]
this issue, seems old, and outdated, the description it's not clear and it's probably referring to the UI
