### ISSUE TITLE
cspell dictionary

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#252]
We should have spell check as part of our commit hook.

> nice catch! but cspell doesn't work properly for some variable names. ie. curveuADBalance fails on spell check. My suggestion is to make an issue if you actually want spell check with ignore words / paths and do it later

For examples like these, we can add "uAD" to the cspell dictionary.

**Comment by sergfeldman** [comment]
@pavlovcik Can this task be offered to bounty hunters?

**Comment by 0x4007** [comment]
Yes but it isn't really spec'd out. Basically we should have a commit hook (lint-staged) to spell check the codebase.

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by 3commascapital** [comment]
hey all, i am going to start working on this issue if no one has a problem with it.
seems pretty straightforward.
- [ ] install cspell
- [ ] iterate on codebase until all errors are gone
- [ ] add into build process

**Comment by 3commascapital** [comment]
how ok are we with modifying solidity property names? found some spelling issues there. i have not dug deep enough into solidity files to know how often contracts are redeployed. generally ok? or just ignore

**Comment by 0x4007** [comment]
Can you post your DAI wallet address here? @3commascapital

**Comment by 0x4007** [comment]
> how ok are we with modifying solidity property names? found some spelling issues there. i have not dug deep enough into solidity files to know how often contracts are redeployed. generally ok? or just ignore

Sorry for missing this comment. That explains your hesitation for editing the solidity files!

**Comment by 3commascapital** [comment]
No worries!

**Comment by 3commascapital** [comment]
@pavlovcik 0x7153Ad46a37573a2EB9EAa6A8644c3f03dfcE6b8

**Comment by 0x4007** [comment]
> @pavlovcik 0x7153Ad46a37573a2EB9EAa6A8644c3f03dfcE6b8

https://etherscan.io/tx/0x555f1bc3ab7aa43eca25adb3ec731d2470a431f06ffd0dad627e6992d68eff50
https://etherscan.io/tx/0x2118856e220a216c80e2a7caed0210fbf352d23d61b4b8fe91ca70faf3de360e

**Comment by 0x4007** [comment]
I was looking to merge `development` into `main` and see that we still have instances of "UbiquityStick" littered all over the code. Currently looking at `packages/dapp/components/bonds/lib/hooks/useLaunchPartyContracts.ts`

I'll update cspell myself eventually to ban this, as well as some other small details.

**Comment by 3commascapital** [comment]
started above in #334
