### ISSUE TITLE
APR calculation broken (property names changed during Foundry conversion?)

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#253]
Somewhere between https://github.com/ubiquity/ubiquity-dollar/compare/389712adb091b2f011574303e96fc837af4e49f6...3f62a1ffadedfb2d85a988c5730d3bbf34f6a2fc you broke the APR calculator on the staking view.

Crashes on https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/staking/DepositShare.tsx#L19

<img width="832" alt="Screen Shot 2022-09-12 at 14 49 28" src="https://user-images.githubusercontent.com/4975670/189590429-f659810d-6fdc-45b5-a760-37b8c704a553.png">

**Comment by 0x4007** [comment]
You changed the data structure of the object (into an array) please investigate any other data structure changes you introduced (and why) during the conversion. You can close the issue after you're sure that there are no other data structure changes or similar issues to this.

The [Uniswap V2 Pair ABI](https://github.com/ubiquity/ubiquity-dollar/blob/development/packages/dapp/components/config/abis/UniswapV2Pair.json#L50-L51) references the removed properties as well.

Fix: https://github.com/ubiquity/ubiquity-dollar/commit/ae9386bfbb70343439d8f390edc52b514182f0d8

**Comment by cuddle-dev** [comment]
that was my bad to remove. I will double check other possible issues similar to described above.

**Comment by cuddle-dev** [comment]
completed

**Comment by 0x4007** [comment]
> please investigate any other data structure changes you introduced (and why) during the conversion

Still curious to know the "why"
