### ISSUE TITLE
UI Test CI

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#257]
Depends on https://github.com/ubiquity/ubiquity-dollar/issues/833

We should prepare UI smoke tests that check that there are no console errors when a new page is opened.

As a part of this issue we should create a new github workflow that runs UI smoke tests (using https://github.com/ubiquity/scraper-kernel) that check that there are no console errors when the following web pages are opened:
1. Home (https://uad.ubq.fi/)
2. Markets (https://uad.ubq.fi/markets)
3. Pool (implemented in https://github.com/ubiquity/ubiquity-dollar/issues/833)

_Original description:_
We should setup [Puppeteer](https://pptr.dev/) on CI to open every view and look for thrown errors.
1. We can iteratively improve the sophistication of the UI tests, but I think this could catch some low hanging fruit/errors.
4. Next we could click all buttons and look for errors.

Inspired by: https://github.com/ubiquity/ubiquity-dollar/issues/253

I have a really good scraper kernel [here](https://github.com/ubiquity/scraper).

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by pwilson77** [comment]
@sergfeldman you can assign this issue to me

**Comment by 0x4007** [comment]
Can you take a look at the [kernel](https://github.com/ubiquity/scraper) and let me know if you have questions before accepting the bounty? To be honest I think I'll need to work directly with you to make this go smoothly. You're probably going to need to be familiar with Puppeteer to perform well on this.

**Comment by pwilson77** [comment]
Sure let me take a look at the kernel

**Comment by 0x4007** [comment]
Basically, you need to organize the page scraping/testing logic in `src/pages` and it maps to the URL structure (can also use wildcards "*") 

If you want to write some test page scraping logic, I suggest that you match the function signature of the [GitHub scraper controller](https://github.com/ubiquity/scraper/blob/03bdf8aae22602e107ed15437c4d0b7dc1abfccf/src/pages/github.com/*/index.ts#L28) (it's the latest page logic I have been working on) 

The scraper automatically exposes `Puppeteer.Browser` and `Puppeteer.Page` which will allow you to do everything you need to manipulate the page with puppeteer.

**Comment by pwilson77** [comment]
hi sorry for the late response, so am basically just organizing the test logic or?

**Comment by 0x4007** [comment]
I'm going to try and merge the kernel with the initial tests so I'm taking this bounty from the pool.

**Comment by kgelpes** [comment]
Is this issue open?

**Comment by sergfeldman** [comment]
> Is this issue open?

@kgelpes This issue is already assigned, so not available to the bounty hunters

**Comment by 0x4007** [comment]
> @kgelpes This issue is already assigned, so not available to the bounty hunters

Technically this is correct, but I would be open to letting @kgelpes try this but we would probably need to redefine it a little bit. 

The vision is to set up Puppeteer on GitHub Actions to automatically run on CI. I think that could be broken into separate bounties:

1. Build Puppeteer code to crawl the UI. + tag a target on the components for the Puppeteer code to click and test. i.e. `[data-puppeteer="click"]`
2. Puppeteer code should be ported to GItHub Actions to be invoked automatically as part of CI.

@kgelpes are you familiar with Puppeteer? If so, I could make 1. into a new bounty.

**Comment by kgelpes** [comment]
> > @kgelpes This issue is already assigned, so not available to the bounty hunters
> 
> Technically this is correct, but I would be open to letting @kgelpes try this but we would probably need to redefine it a little bit.
> 
> The vision is to set up Puppeteer on GitHub Actions to automatically run on CI. I think that could be broken into separate bounties:
> 
> 1. Build Puppeteer code to crawl the UI. + tag a target on the components for the Puppeteer code to click and test. i.e. `[data-puppeteer="click"]`
> 2. Puppeteer code should be ported to GItHub Actions to be invoked automatically as part of CI.
> 
> @kgelpes are you familiar with Puppeteer? If so, I could make 1. into a new bounty.

I can create tests for puppeteer to test simple stuff like clicking buttons, also taking screenshots so that we can check there's no visual anomalies on builds

**Comment by olich97** [comment]
Hello @pavlovcik, would you like to consider using [playwright](https://github.com/microsoft/playwright) instead of `puppeteer` for UI testing in this case?
I think it could be a nice fit for this project as playwright has an easy and clean way to writing tests and integrates gracefully with GitHub CI, more info:
- [Writing tests](https://playwright.dev/docs/writing-tests#first-test)
- [CI GitHub Actions](https://playwright.dev/docs/ci-intro)
- [Capture/check console errors](https://playwright.dev/docs/api/class-consolemessage) ([example](https://github.com/microsoft/playwright/issues/5546#issuecomment-783425772))

**Comment by 0x4007** [comment]
No because we have existing infrastructure with puppeteer. Check @ubiquity/scraper-kernel. The reason why puppeteer was chosen is because it is developed and supported by the chrome team.

**Comment by olich97** [comment]
Understood, many thanks for the clarification 👍

**Comment by PhantomCracker** [comment]
Hello @pavlovcik , I would like to work on this.
Do you think that we can schedule a call or to chat somewhere out of github?

**Comment by molecula451** [comment]
i can tackle this one after #685 closes

**Comment by rndquu** [comment]
This task is not ready because we first need to update UI to follow the diamond contracts deploy

**Comment by molecula451** [comment]
> This task is not ready because we first need to update UI to follow the diamond contracts deploy

let's work on it together

**Comment by 0x4007** [comment]
> This task is not ready because we first need to update UI to follow the diamond contracts deploy

@rndquu is there an update on this?

**Comment by rndquu** [comment]
> > This task is not ready because we first need to update UI to follow the diamond contracts deploy
> 
> @rndquu is there an update on this?

@molecula451 will you handle this one https://github.com/ubiquity/ubiquity-dollar/issues/731 ? If not then I'll take it

**Comment by molecula451** [comment]
> > > This task is not ready because we first need to update UI to follow the diamond contracts deploy
> > 
> > 
> > @rndquu is there an update on this?
> 
> @molecula451 will you handle this one #731 ? If not then I'll take it

Yes I will handle the UI at #731 asap. I would have tell you otherwise

**Comment by 0x4007** [comment]
- #731 appears to be completed!

**Comment by rndquu** [comment]
> * [Add UI diamond hook #731](https://github.com/ubiquity/ubiquity-dollar/issues/731) appears to be completed!

The UI is still broken so the current issue is still blocked

I will add new UI related tasks today

**Comment by molecula451** [comment]
Unfortunately the #731 was mislead, because the specs mention to add a hook, keep the hook, or fix it, in any case, this was never the case, the contracts are being fetching in another way, but this was all part of the debug. We would have never known the bad state  of this hook without working up through all those opened (now closed) issues.

**Comment by 0x4007** [comment]
@gentlementlegen this seems like your territory, just not a high priority item at the moment.

**Comment by PhantomCracker** [comment]
> @gentlementlegen this seems like your territory, just not a high priority item at the moment.

If is ok I can also work on this.

**Comment by 0x4007** [comment]
> > @gentlementlegen this seems like your territory, just not a high priority item at the moment.
> 
> If is ok I can also work on this.

Check out the Cypress setup on our https://github.com/ubiquity/ts-template it should get you most of the way there.

**Comment by rndquu** [comment]
It makes sense to wait with this issue until https://github.com/ubiquity/ubiquity-dollar/issues/833 is ready

**Comment by 0x4007** [comment]
> It makes sense to wait with this issue until #833 is ready

I think they can get started. The idea is meant to be generalized to throw in the CI if any errors are found when loading any views. 

In this case, it would mean just adding another line of code, a click on the menu navigation, to load the view for #833

**Comment by PhantomCracker** [comment]
> ```diff
> ! No price label is set, so this is not ready to be self assigned yet.
> ```

@0x4007 can you please set a price so I can assign it also?

**Comment by rndquu** [comment]
As far as I understand it is already implemented [here](https://github.com/ubiquity/onboard.ubq.fi/blob/development/.github/workflows/cypress-testing.yml) so we should move that workflow to this repo and make sure that it works properly

**Comment by 0x4007** [comment]
> ```diff
> - Error: duplicate key value violates unique constraint "new_users_pkey" 

@gentlementlegen I'm assuming both bots are writing to the same database or something?

**Comment by 0x4007** [comment]
Also @rndquu im assuming that we should close this as unplanned because it seems like we have a new UI underway at ubiquity/uusd.ubq.fi and we use cypress. 

@alexandr-masl its in your best interest to wait for a confirmation before working on this as per the start message warning

**Comment by gentlementlegen** [comment]
> > ```diff
> > - Error: duplicate key value violates unique constraint "new_users_pkey" 
> > ```
> 
> @gentlementlegen I'm assuming both bots are writing to the same database or something?

That is correct.

**Comment by alexandr-masl** [comment]
> Also @rndquu im assuming that we should close this as unplanned because it seems like we have a new UI underway at ubiquity/uusd.ubq.fi and we use cypress. 
> 
> @alexandr-masl its in your best interest to wait for a confirmation before working on this as per the start message warning 

Understood. I will await your update

**Comment by rndquu** [comment]
Yes, this is already implemented in https://github.com/ubiquity/uusd.ubq.fi/blob/development/.github/workflows/cypress-testing.yml so this issue may be closed as "not planned".
