### ISSUE TITLE
UI Request: Automatically Detect UBQ/UAD Token in User Wallet

### ISSUE THREAD

**Issue by AprilexSedLex** [ubiquity/uad-ui#26]
It gets pretty hard when your moving around your Metamask and have to add in all the previous coin and hunt for addresses. I suggest a way to automatically detect if UBQ or uAD is in user wallet and automatically suggest to add in a pop up maybe if its not already there.

**Comment by Zequez** [comment]
Is there an API from Metamask to suggest tokens like this? @pavlovcik

**Comment by 0x4007** [comment]
Not sure of an API but I'm sure you can find some open source software for it!

**Comment by Zequez** [comment]
This might be it:

https://ethereum.stackexchange.com/questions/99343/how-to-automatically-add-a-custom-token-to-metamask-with-ethers-js

**Comment by Zequez** [comment]
Then there is this: https://consensys.net/blog/metamask/how-to-use-metamasks-token-detection-feature/

**Comment by marcomow** [comment]
a "+" next to each token, clicking it adds the token to metamask
