### ISSUE TITLE
Create UBQ bonding curve to burn UBQ and mint NFTs

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/uad-ui#264]
- Create the UBQ bonding curve smart contract (fork)
- Update UI component 
- Implement the logic "Buy with any token" 
1. Get the tokens that the user has
2. Exchange to UBQ
3. Send UBQ to bonding curve contract (effectively burning it)
4. Mint UbiquiStick NFT
5. Transfer the UbiquiStick NFT to the buyer

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
@codeawayaks We offer solving bounties one at a time to minimize blocking other developers to move things forward. Which one issue you want to work on first?

**Comment by pufferdev0807** [comment]
@sergfeldman I am very interested about this task.
But I need your explain a bit more.

**Comment by sergfeldman** [comment]
> @sergfeldman I am very interested about this task. But I need your explain a bit more.

@pufferdev0807 Please, post your clarifying questions here.
We will make a decision on assigning you after you ask questions.

**Comment by zgorizzo69** [comment]
hello @sergfeldman I am very familiar with bonding curve (bancor formula) as you can see here https://github.com/meTokens/meTokens-core
and I get what you want to do here :smile: 
 let me know if I can work on it

**Comment by Draeieg** [comment]
@zgorizzo69 Already did most of the mathematical modeling for this just need to refine a few parameters https://www.desmos.com/calculator/o311zdypy1, we can hop on a call for more details if the decision is to have you working on this

**Comment by zgorizzo69** [comment]
> @zgorizzo69 Already did most of the mathematical modeling for this just need to refine a few parameters https://www.desmos.com/calculator/o311zdypy1, we can hop on a call for more details if the decision is to have you working on this

Sure ! Let's wait for @sergfeldman @pavlovcik decision then

**Comment by 0x4007** [comment]
> hello @sergfeldman I am very familiar with bonding curve (bancor formula) as you can see here https://github.com/meTokens/meTokens-core and I get what you want to do here 😄 let me know if I can work on it

That's dope but I feel like this particular bounty is quite low in our priority list. Given your experience with this project and Solidity expertise, your contributions will be more impactful if we have you focus on the more important issues you have also expressed interest in.

**Comment by sergfeldman** [comment]
Note for the bounty hunters.

This issue should be divided to smaller tasks with the specific deliverables.
For example, 
1. Update the UI component.
2. Implement the logic "Buy with any token".

Please, suggest smaller tasks when apply for this bounty.

**Comment by 0x4007** [comment]
> This issue should be divided to smaller tasks with the specific deliverables. For example,
> 
> 1. Update the UI component.
> 2. Implement the logic "Buy with any token".
> 
> Please, suggest smaller tasks when apply for this bounty.

I encourage you to break up the issue into separate issues. It should be on us to do that.
