### ISSUE TITLE
Unit tests conversion in Foundry

### ISSUE THREAD

**Issue by cuddle-dev** [ubiquity/uad-ui#269]
## Problem
We're converting the smart contract packages from hardhat to foundry. Its being tracked [here](https://github.com/ubiquity/ubiquity-dollar/pull/261).  Unit tests conversion is the largest remaining part and its already being handled by @0xcodercrane. 
But to do that conversion faster, we're gonna break into small ones. 

## What should I do?

You need to create fuzz tests for the following files. Others will be done by @0xcodercrane .

- [x] [dollar/BondingV2.sol](https://github.com/ubiquity/ubiquity-dollar/blob/feat/foundry-conversion/packages/contracts/src/dollar/BondingV2.sol), 
- [x] [dollar/BondingShareV2.sol](https://github.com/ubiquity/ubiquity-dollar/blob/feat/foundry-conversion/packages/contracts/src/dollar/BondingShareV2.sol), 
- [x] [dollar/MasterChefV2.sol](https://github.com/ubiquity/ubiquity-dollar/blob/feat/foundry-conversion/packages/contracts/src/dollar/MasterChefV2.sol), 
- [x] [ubiquistick/SimpleBond.sol](https://github.com/ubiquity/ubiquity-dollar/blob/feat/foundry-conversion/packages/contracts/src/ubiquistick/SimpleBond.sol)

## Acceptance Criteria
Unit test files (*.t.sol) should be able to cover most functions as much as possible

**Note** The active branch for foundry conversion is `feat/foundry-conversion`. so it is needed to rebase from that branch and create a pull request to the feat/foundry-conversion branch.

**Comment by hashedMae** [comment]
I can have this done by next Wednesday for 800 USDC

**Comment by hashedMae** [comment]
https://github.com/ubiquity/ubiquity-dollar/pull/275

**Comment by hashedMae** [comment]
https://github.com/ubiquity/ubiquity-dollar/pull/278

**Comment by cuddle-dev** [comment]
hey @hashedMae . it looks like simpleBond is missing right now. if you've done it locally, would you push it?

**Comment by hashedMae** [comment]
It's there. I created a ubiquistick folder under tests to mimic the layout in src

https://github.com/ubiquity/ubiquity-dollar/blob/feat/foundry-conversion/packages/contracts/test/ubiquistick/SimpleBond.t.sol

**Comment by cuddle-dev** [comment]
oh my bad! thank you for confirming

**Comment by cuddle-dev** [comment]
ERC20 USDC: 0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46

**Comment by hashedMae** [comment]
ERC20 USDC
0x7fe65D99a0998Cdba8e1f749303a467dcf87e815

**Comment by sergfeldman** [comment]
> 

@0xcodercrane Thank you for the bounty review
https://etherscan.io/tx/0x238460a17fed6f694f3616e01caa63d922188e1a35bc13d7e90a75f9faa5d484

**Comment by sergfeldman** [comment]
> 

@0xcodercrane This transaction passed https://etherscan.io/tx/0x5f7f82bbe62154288b5e8aa16527a2c3cbac40e68c91af9050879c1b92a37173

**Comment by sergfeldman** [comment]
> ERC20 USDC 0x7fe65D99a0998Cdba8e1f749303a467dcf87e815

@hashedMae Welcome to the core team
https://etherscan.io/tx/0x9d9da7266d07e6c01f77e75649592b9d1975108a9edc7c1a457f42721017876a
https://etherscan.io/tx/0xb0f7adfc86ff8fffbcae5a234658f048ca051509f2d21514b305608ec6a68dcd
