### ISSUE TITLE
uCR-NFT Cashback UI should be the same as uCR Cashback UI

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#280]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/4975670/194260211-87ef3f8f-1d3f-42dc-8233-a8371a74ff89.png">

Also what does the white dropdown $1.00232 mean? Update: its the uCR-NFT but this should be visible when above peg. Also should not be prefixed with "$" unless it includes the spot price calculation of uAD

_Original post https://github.com/ubiquity/ubiquity-dollar/pull/279#issuecomment-1269562876_

User flow and UI code can be copied from the uCR Cashback UI components. I imagine that this can be done within a couple of days

**Comment by kingsley-einstein** [comment]
I'd like this issue to be assigned to me.

**Comment by 0x4007** [comment]
> I'd like this issue to be assigned to me.

Sure but I have to warn you that it'll require you to probably work pretty closely with @sunny0714 as he is still currently implementing the prerequisite component. It'll be much easier to work on this once he is done.

**Comment by kingsley-einstein** [comment]
> > I'd like this issue to be assigned to me.
> 
> Sure but I have to warn you that it'll require you to probably work pretty closely with @sunny0714 as he is still currently implementing the prerequisite component. It'll be much easier to work on this once he is done.

I'll keep communications with him thorough. I'll consider all available options and take the most productive one.

**Comment by 0x4007** [comment]
One other detail to note: because we can't guarantee liquidity to sell uCR-NFT on OpenSea etc; this component should only be visible above peg. 

We CAN guarantee liquidity above peg because our smart contract allows Credit (uCR-NFT) to Dollar (uAD) redemption, which in turn can be converted to other stables in the Dollar 3pool (uAD/DAI/USDC/USDT)

**Comment by sergfeldman** [comment]
> I'd like this issue to be assigned to me.

@kingsley-einstein The bounty price is 200 USDC

**Comment by kingsley-einstein** [comment]
> > I'd like this issue to be assigned to me.
> 
> @kingsley-einstein The bounty price is 200 USDC

Alrighty!

**Comment by 0x4007** [comment]
Bad news is that it looks like we're going with a Uniswap widget which is designed for fungible tokens. To make the uCR-NFT cashback UI match will be a steeper challenge. I plan to personally dive in and customize the Uniswap widget to look less Uniswap-y. Once I do that, I imagine we'll have a more clear idea of exactly what needs to be done for this (#280) issue

**Comment by acaldas** [comment]
Hey @pavlovcik, what's the status of this issue? Is it something I can work on?

**Comment by 0x4007** [comment]
Unfortunately we have a cascade of blockers for this bounty at this moment in time. 

1. the UI is unstable on `development`
2. we need to test the uniswap UI widget but we can't because 
3. we need to manipulate the price of uAD but
4. we can't swap on the uAD market because crv.to UI is broken (not ours)

So basically blockers currently are:

1. we need to make `development` UI stable and then (multiple issues I can't find off hand)
2. migrate to a v3 Curve Metapool to be able to swap on curve.fi, #295

**Comment by 0x4007** [comment]
Closing because we don't have plans to redeploy with credits for the foreseeable future.
