### ISSUE TITLE
Import `@Uniswap/smart-order-router` to accurately predict uCR cash out amounts

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#282]
Im reading this now. The return value looks familiar.

 https://github.com/Uniswap/smart-order-router

Probably a bad idea but the first thing that comes to mind is to browserify (this transpiler exists) the node project. We could make a separate Git fork that handles this and import the submodule into the component that needs it. 

That would probably have to be a new bounty because that seems like it's own project. Any other ideas?

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/279#issuecomment-1271037058_

**Comment by 0x4007** [comment]
I just realized that Next.js, what we are using in our UI, has server side (Node runtime) rendering/processing capabilities. We might be able to directly include the package in our UI without having to "browserify"

I really hope that Tenderly is not a mandatory dependency because we only get 50 free simulations per month, unless we pay a lot of money for a "pro" account.

**Comment by 0xautohub** [comment]
Hey, @pavlovcik did you try to run build smart order router repo?
I have some errors.. hope you to try and help me to run the project

**Comment by 0xautohub** [comment]
![image](https://user-images.githubusercontent.com/5579669/194548918-c107cae7-a3e6-4046-bc70-b12ee6d2edf7.png)

**Comment by 0x4007** [comment]
> ![image](https://user-images.githubusercontent.com/5579669/194548918-c107cae7-a3e6-4046-bc70-b12ee6d2edf7.png)

Try generating the types by running typechain

**Comment by 0xautohub** [comment]
Yeah, if execute "yarn run build", it generates types automatically, but the typechain path has some issue? or I'm not familiar with it yet

**Comment by 0xautohub** [comment]
![image](https://user-images.githubusercontent.com/5579669/194549634-7618f7fd-68b7-4efc-ae5a-0f733dfb1fdc.png)
I also had to remove some path, but not sure I was right
I didn't get their intention to write the path like "?(v3-core|v3-periphery)"

**Comment by 0x4007** [comment]
Just copy their CI. It builds there. https://github.com/Uniswap/smart-order-router/actions/runs/3184789100/jobs/5193604243

**Comment by 0xautohub** [comment]
Cool, thanks

**Comment by 0xautohub** [comment]
> Just copy their CI. It builds there. https://github.com/Uniswap/smart-order-router/actions/runs/3184789100/jobs/5193604243

Just checked, no special thing

**Comment by 0x4007** [comment]
Their tests work so the code builds, and functions without errors. Learn how to use their code by seeing how the tests use the code.

**Comment by 0xautohub** [comment]
> 

Yeah, their CI works, seems the error was generated because I'm on Windows

**Comment by 0xautohub** [comment]
Oh.. it was not, I got same error when running in Ubuntu 😢
![image](https://user-images.githubusercontent.com/5579669/194553302-f64639c4-9368-4e10-aef0-3d242dba033e.png)

**Comment by 0x4007** [comment]
@ubiquity/development any ideas for @sunny0714

**Comment by cuddle-dev** [comment]
`npm run build` should generate types for each package. Anyway I tried locally on macOS but 3 commands (npm, npm run build, npm run test) were successful.  but it should also work on ubuntu latest. Their github workflow is the proof of its working. 

@pavlovcik  @sunny0714

**Comment by 0xautohub** [comment]
@0xcodercrane Thanks for your try. Yeah, I have already found it at that time. I used yarn, so when installing packages, package-lock.json was not reflected.
I have almost finished this feature, going to finish by today or tomorrow

**Comment by 0xautohub** [comment]
Hey @pavlovcik @0xcodercrane The uCR cash out amount is being shown accurately on [this commit](https://github.com/ubiquity/ubiquity-dollar/pull/279/commits/d8237b778c83727dd9078ece8eb87389b2ef7d5b)
Fortunately, smart order router is not using tenderly for integration
Please review it when you are available

**Comment by 0xautohub** [comment]
Uniswap widget was reflected on [this commit](https://github.com/ubiquity/ubiquity-dollar/pull/279/commits/55d8166e87f3dd78e687fd7a40800eb0aa40c324)

**Comment by 0x4007** [comment]
> `npm run build` should generate types for each package. Anyway I tried locally on macOS but 3 commands (npm, npm run build, npm run test) were successful.

We should always be using `yarn` why are you @0xcodercrane talking about `npm`? Otherwise, then we have issues with the lockfile as @sunny0714 mentioned

**Comment by 0x4007** [comment]
I discussed with @sunny0714 and he makes a claim about how both bounties are done. I discussed with the @ubiquity/bounty-masters and there was pushback on releasing both bounties because we are unable to test the cash out UI flow (many related systems seem to have broken @0xcodercrane hopefully you have updates on the workaround) 

But this router seems to work and I think it's fine to consider this bounty complete and to release funds. 

@sunny0714 if you can post your wallet address. @sergfeldman if you can release funds - I'll be away from my computer for the evening. Thanks!

**Comment by 0xautohub** [comment]
okay @pavlovcik thanks
Here is my wallet address
0xc6fa133f3290e14Ad91C7449f8D8101A6f894E25

**Comment by 0xcodercrane** [comment]
We have been struggling to test the cashout UI but unfortunately no way so far.  its really difficult without fixing our broken system but codebase looks good, router seems to work properly. 

We appreciate doing good job @sunny0714. Right now we are unable to test because of the blocker. but we want to trust it will absolutely work once we resolve our blocker, but in worse case (e.g. not working), if we ping you with the problem , you will definitely help us right? @sunny0714

**Comment by cuddle-dev** [comment]
> I discussed with @sunny0714 and he makes a claim about how both bounties are done. I discussed with the @ubiquity/bounty-masters and there was pushback on releasing both bounties because we are unable to test the cash out UI flow (many related systems seem to have broken @0xcodercrane hopefully you have updates on the workaround)
> 
> But this router seems to work and I think it's fine to consider this bounty complete and to release funds.
> 
> @sunny0714 if you can post your wallet address. @sergfeldman if you can release funds - I'll be away from my computer for the evening. Thanks!

We have been struggling to test the cashout UI but unfortunately no way so far. its really difficult without fixing our broken system but codebase looks good, router seems to work properly.

We appreciate doing good job @sunny0714. Right now we are unable to test because of the blocker. but we want to trust it will absolutely work once we resolve our blocker, but in worse case (e.g. not working), if we ping you with the problem , you will definitely help us right? @sunny0714

Agree to consider his bounty complete and release funds!!!

**Comment by 0xautohub** [comment]
Yeah, thanks for saying so @0xcodercrane 
I will definitely fix issues if there are any problems

**Comment by cuddle-dev** [comment]
We will appreciate it! I will merge your pull request

**Comment by sergfeldman** [comment]
> [sunny0714](/sunny0714)

@sunny0714 Thank you for the completed bounty 
https://etherscan.io/tx/0xdd2ef921a5e7272bb379adc12b259a924ffc7f92570686642208bb8a272cd22e

**Comment by 0x4007** [comment]
> @sunny0714 Thank you for the completed bounty https://etherscan.io/tx/0xdd2ef921a5e7272bb379adc12b259a924ffc7f92570686642208bb8a272cd22e

In the future @sergfeldman please be sure to 
1. Include any applicable UBQ bonuses according to the calculations [listed here](https://github.com/ubiquity/ubiquity-dollar/wiki/Bounty-Compensation).
2. Close the issue 

Update: looks like it took two weeks to finish this bounty, so there are no applicable UBQ bonuses!

**Comment by sergfeldman** [comment]
> > @sunny0714 Thank you for the completed bounty https://etherscan.io/tx/0xdd2ef921a5e7272bb379adc12b259a924ffc7f92570686642208bb8a272cd22e
> 
> In the future @sergfeldman please be sure to
> 
> 1. Include any applicable UBQ bonuses according to the calculations [listed here](https://github.com/ubiquity/ubiquity-dollar/wiki/Bounty-Compensation).
> 2. Close the issue
> 
> Update: looks like it took two weeks to finish this bounty, so there are no applicable UBQ bonuses!


Note for the future. 

This issue has not a usual resolution.
The bounty considered as completed, but the issue is not tested.

The dedicated issue for testing is created
https://github.com/ubiquity/ubiquity-dollar/issues/297

This issue is closed.

**Comment by 0x4007** [comment]
> This issue has not a usual resolution. The bounty considered as completed, but the issue is not tested.
> 
> The dedicated issue for testing is created #297

Technically, the Uniswap router does apparently work (it displays the estimated swap values already in the UI) the other issue is what needs testing as there is functionality dependent on those numbers returned by the router.
