### ISSUE TITLE
DAI Missing on Inventory

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#283]
This wallet has plenty of DAI in it but for some reason it isn't showing. Make sure that the inventory shows DAI and USDT!

<img width="938" alt="image" src="https://user-images.githubusercontent.com/4975670/194712350-91f72a75-0878-4994-89b8-016b32cfbe47.png">

**Comment by trydev0303** [comment]
I think the balaceOf() function is not working properly due to web3 connection
I will try but where can I start?

**Comment by sergfeldman** [comment]
@pavlovcik Can you please provide your input here?

**Comment by 0x4007** [comment]
> I think the balaceOf() function is not working properly due to web3 connection I will try but where can I start?

What you're saying doesn't make sense to me. The RPC connection is fine, that's how all the other balances were successfully queried.

**Comment by trydev0303** [comment]
I don't mean RPC connection.
The token balances are queried by calling the balanceOf() function of token contract with the parameter of account address.
If account address is correct, then the problem is the token contract consisted of contract address and ERC20 ABI.

**Comment by trydev0303** [comment]
please let me know the account address.
Then I will check on my side.

**Comment by 0x4007** [comment]
> please let me know the account address. Then I will check on my side.

It should be [ubq.eth](https://etherscan.io/address/ubq.eth)

**Comment by trydev0303** [comment]
![image](https://user-images.githubusercontent.com/102959685/195396648-2b48b21e-be45-499a-b2ff-d359bef2bd1d.png)
yep it is working on etherscan and showing the DAI balance of ubq.eth
so we can say that the web3 connection of DApp is error.
pls send me your code and I will fix it.

**Comment by 0x4007** [comment]
> ![image](https://user-images.githubusercontent.com/102959685/195396648-2b48b21e-be45-499a-b2ff-d359bef2bd1d.png) yep it is working on etherscan and showing the DAI balance of ubq.eth so we can say that the web3 connection of DApp is error. pls send me your code and I will fix it.

lol open a PR from this repo

**Comment by trydev0303** [comment]
I have tried but cannot start the project

**Comment by 0x4007** [comment]
You can always refer to the CI/CD scripts that install, build and run the projects.

https://github.com/ubiquity/ubiquity-dollar/blob/development/.github/workflows/install-and-build-pr.yml

**Comment by mastercodechef** [comment]
![image](https://user-images.githubusercontent.com/102959685/195400918-5597a705-d5d5-4bfd-9f5e-ff27c4957ee0.png)

**Comment by cuddle-dev** [comment]
> ![image](https://user-images.githubusercontent.com/102959685/195400918-5597a705-d5d5-4bfd-9f5e-ff27c4957ee0.png)

hey @mastercodechef . this is sort of workspace project. You can quickly take a look at the following link to figure out how it works, how to run individual package. 

https://classic.yarnpkg.com/lang/en/docs/workspaces/

so you need to run `yarn` in the root directory to install packages which installs all the dependencies required in this workspace. 
To build the individual package like dapp package, run the command `yarn workspace @ubiquity/dapp build`

**Comment by trydev0303** [comment]
![image](https://user-images.githubusercontent.com/102959685/195417375-fe2806bc-53df-4988-97be-37d1be7c876e.png)

Hi @0xcodercrane pls help me

**Comment by cuddle-dev** [comment]
1. `yarn`
2. `yarn build:all` -- To do this, you need to install foundry on your os. Here is a install guide. https://book.getfoundry.sh/getting-started/installation
`yarn build:all` includes `yarn workspace @ubiquity/dapp build` as well. Please go through the package.json in the root directory
3. `yarn workspace @ubiquity/dapp start`

@mastercodechef

**Comment by trydev0303** [comment]
![image](https://user-images.githubusercontent.com/102959685/195516198-19f6d133-6166-4ce8-a25a-da901fef55e5.png)
Thank you, @0xcodercrane.
I think I have done it.
The DAI balance of my account is displaying.

**Comment by trydev0303** [comment]
https://www.impersonator.xyz/ requires walletconnect but
![image](https://user-images.githubusercontent.com/102959685/195641888-24f864c7-c473-4e34-ba94-9a059734ed73.png)
ubiquity dapp does not have walletconnect

**Comment by trydev0303** [comment]
That's why I cannot use impersonator to pretend as ubq.eth.
I thought this issue was from ENS.
So I tried with my ENS but it is still working on my side.
In my opinion we are fetching the balance for ubq.eth but cannot show.
We can check this by console.log as I suggested before.

**Comment by 0x4007** [comment]
I just realized that `production` is just out of date. @ubiquity/bounty-masters we should figure a process to make sure stuff like this doesn't happen again.

https://531ffccd.ubiquity-dollar-development.pages.dev/ from https://github.com/ubiquity/ubiquity-dollar/runs/8485554679

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/4975670/195695687-368c68de-83d1-4661-bdf6-b72480e94597.png">
