### ISSUE TITLE
Upgrade smart contracts to resolve well-known vulnerabilities.

### ISSUE THREAD

**Issue by cuddle-dev** [ubiquity/uad-ui#284]
## Problem
Once we have slither integrated into the github ci/cd, it has picked up lots of well-known vulnerabilities. 
This will absolutely block us to become a stable product.

## Reference
https://github.com/ubiquity/ubiquity-dollar/actions/runs/3216583130/jobs/5258613067

**Comment by cuddle-dev** [comment]
we created a fix-slither branch which contains slither ci/cd. if you wanna hop in this issue, you need to rebase from fix-slither branch.

**Comment by hashedMae** [comment]
Summary of tasks/errors

- [ ] ABDKMath should be installed like the other Foundry libraries since it's not a library we maintain. 
- [ ] Some of the unused local variables can likely just be removed and others might of been missed in implementation (the ones within tests and mocks)
- [ ] Lots of not following style guide for naming
- [ ] Changing contracts to use a consistent version and not `^0.x.x` versions
- [ ] Fix breaking changes where they come up
- [ ] not following strict Check Effects Interaction Patterns, some may require light re-engineering to correct
- [ ] Return values being ignored, either don't ignore them or the function doesn't need to return a value
- [ ] Some functions that should emit events don't
- [ ] No zero address check on setters
- [ ] Gas efficiencies, external call to get an address inside of a loop instead of setting a local variable before loop
- [ ] Contracts not inheriting from their interfaces

**Comment by 0x4007** [comment]
> * Lots of not following style guide for naming

Speaking of naming, as I mentioned to @0xcodercrane before, I would like to update all of the product names to reduce ambiguity (for example the Bonding contract should be called Staking.)

The biggest technical hurdle I see for the rename/redeploy of these contracts would be the user funds in Bonding contract. We would need to do a migration. I'm curious to know how complex the migration would be. 

From what I understand, everything else can be replaced/upgraded via our `UbiquityAlgorithmicDollarManager.sol`

**Comment by hashedMae** [comment]
I'm going to put my estimate at 100 hours over 3 weeks for 5000 USDC. I can track my hours and provide weekly updates on progress. Plan is to tackle the simplest issues first, that way if any blockers come up, they'll be later in the process and less likely to impede other issues (ie. Changing solidity version and CEI patterns will come last)

**Comment by 0x4007** [comment]
@0xcodercrane lets connect later today to verify the spec together before we continue the conversation

**Comment by cuddle-dev** [comment]
@hashedMae  I will keep you updated what is necessary/unnecessary. so we want to cut out some items from the list you created.

**Comment by hashedMae** [comment]
The solidity versioning and CEI patterns are the two most important and also the largest tasks that will take up the majority of the time.

**Comment by cuddle-dev** [comment]
> The solidity versioning and CEI patterns are the two most important and also the largest tasks that will take up the majority of the time.

thats what I am working right now. 

https://github.com/ubiquity/ubiquity-dollar/pull/302/commits/29300d86a45d2ff71b12154a36634a320a0aaa92
this is the final commit I pushed. you can reestimate everything and take this issue over. @hashedMae

**Comment by hashedMae** [comment]
I think I can get the rest done for $3000 USDC within two weeks

**Comment by cuddle-dev** [comment]
Could you do this for $2000 within two weeks? I think I already made it much less than before and we don't want to spend like that because this isn't either urgent or critical.

**Comment by hashedMae** [comment]
It’s still throwing quite a few reentry warnings cause of CEI patterns which will take a bit of re-engineering to correct

**Comment by 0x4007** [comment]
My intuition is that we should settle in the middle, at $2500, in order to unblock @hashedMae from beginning.

**Comment by cuddle-dev** [comment]
ok @hashedMae seems kind of busy recently and would be more busy for chicken bond implementation in the future. let me continue this bounty.

**Comment by cuddle-dev** [comment]
@hashedMae. would you have a mind to continue this issue? I also made some progress (I might say lots of progress) but yeah I need to switch to setup infra which looks most blocker. you can continue on this issue for the @pavlovcik 's latest budget if you want. 

tldr: 34 results still remaining

**Comment by hashedMae** [comment]
I can wrap up the tiny bonds report today and then get started on this

**Comment by 0x4007** [comment]
@0xcodercrane I think we should technically wait until @hashedMae is ready to assign. It'll help make this a standard process for when the bounty bot starts working with us (keeps track of time for a bounty.)

**Comment by cuddle-dev** [comment]
hey @hashedMae. you might need to post your address to pay and complete the issue.
Price tag has been updated by bot from 2500 usd. lol @pavlovcik

**Comment by hashedMae** [comment]
0x7fe65D99a0998Cdba8e1f749303a467dcf87e815

**Comment by 0x4007** [comment]
https://etherscan.io/tx/0x6838e8e57b498fb7934ef4e5866befbe6c262eb7e9d1b92be902df06d19539d7
https://etherscan.io/tx/0xd50647bc8924ba0bd38e751f8a7ffd8117255fb3f772e5a2ffa9944f6f0ccb21

Happy holidays!
