### ISSUE TITLE
Cross-platform installation & setup instructions in README

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#287]
Once the Foundry conversion is done, the README should clearly explain how to start the project for macOS, Windows, and Ubuntu. This is a just a small note I'm leaving here so that it's not forgotten about!

**Comment by cuddle-dev** [comment]
updated readme for the workspace and contract package here: https://github.com/ubiquity/ubiquity-dollar/commit/b244938f0718bb14d5b7f9219d139d13cf046ba7b

**Comment by 0x4007** [comment]
> updated readme for the workspace and contract package here: [b244938](https://github.com/ubiquity/ubiquity-dollar/commit/b244938f0718bb14d5b7f9219d139d13cf046ba7b)

404 - not found

**Comment by cuddle-dev** [comment]
> > updated readme for the workspace and contract package here: [b244938](https://github.com/ubiquity/ubiquity-dollar/commit/b244938f0718bb14d5b7f9219d139d13cf046ba7b)
> 
> 404 - not found

that was done in foundry-conversion branch. we can't see it anymore because the branch got deleted

**Comment by 0x4007** [comment]
It was not found seven days ago. Besides, just because a branch was deleted doesn't mean that the commit is deleted. The commit is merged in with the branch.

**Comment by cuddle-dev** [comment]
hmm interesting. Let me double check

**Comment by 0x4007** [comment]
Manually looking at the README, it appears that the only incorrect section is referring to the mnemonic that you and I had a conversation around. Either you should restore the original one, or you should update the five private keys generated from the new mnemonic in the readme for developer convenience.

See https://github.com/ubiquity/ubiquity-dollar#metamask-development-wallet-setup

**Comment by cuddle-dev** [comment]
Its getting resolved in the following 2 commits.

https://github.com/ubiquity/ubiquity-dollar/commit/0f0e37b007cd6aa7f0a158bb29b6317870468a89
https://github.com/ubiquity/ubiquity-dollar/commit/02693ba790aaafe03000825f0f6c48c76fd43d34
