### ISSUE TITLE
Refactor and update Ubiquity Inventory component

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#29]
- We use USDC now as part of the Proxy Yield aggregator, so maybe we could add it there.
- Also the component should be updated to prevent horizontal scrollbars.
- Should be mobile-friendly
- There is also a possible refactor to re-use code and not have to have a separate component for each currency; I did this on the [context-refactoring branch](https://github.com/pavlovcik/uad-ui/tree/enhancement/app-context-refactoring) and it looked pretty neat.

**Comment by 0x4007** [comment]
Yeah adding the other stables in there, USDT, DAI, USDC makes sense I think! We would rename it from "Ubiquity Inventory" to "Inventory" as those stables aren't specific to our project.
