### ISSUE TITLE
Pre-calculate gas fees, consolidate transactions, show number of transactions

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#30]
Right now on the yield aggregator when you deposit you have to make 4 different transactions. 3 for approval of ERC20 tokens spending (for USDC, UBQ and uAD), and one for the actual contract call. Locally it costs nothing, sure, but it could stack up to a sizable sum on Mainnet.

Can this be all integrated into a single transaction on the contract call? Can we just call the ERC20 tokens `allowance` method from within our contract? @zgorizzo69

**Comment by 0x4007** [comment]
Could always tag in @zapaz as well for info

**Comment by Zequez** [comment]
@pavlovcik  you mentioned about setting the allowance to infinity; while it's a better user experience it puts a dent on the security, I think the better approach (which is what Curve and Zapper do) is to allow users to pick the allowance (and allow them to set it to infinity if they want); so maybe a sort of allowance-management UI when we need allowances?

I'm closing this and created a separate issue: https://github.com/ubiquity/uad-ui/issues/85
