### ISSUE TITLE
Yield Aggregator - Ready deployment to Mainnet

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#33]
At the moment the UI is working with a hardcoded address from the YieldProxy contract when deployed locally with Hardhat. When we deploy to Mainnet, we'll need to update this. 

The PR for the yield proxy on the uad-contracts repo is here https://github.com/ubiquity/uad-contracts/pull/58

**Comment by 0x4007** [comment]
@zgorizzo69 is finishing the deployment script today. Without it, the contracts can not be deployed.

**Comment by 0x4007** [comment]
Fixed in 518f4d927c5b548c50fd4a7f72017344c2168566
