### ISSUE TITLE
Yield Aggregator - Tooltip component for question mark icons

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#35]
<img width="626" alt="Captura de Tela 2021-10-14 às 13 26 50" src="https://user-images.githubusercontent.com/126037/137358688-434be83b-aab2-4a30-bb15-76c02a51b098.png">

Right now when you hover on the question mark icons you get the standarnd HTML title response; we should show an instant tooltip component that:

- Is displayed when you hover the mouse instantly
- Also works on touch screens
- Keeps the site style

----

Tooltips helper texts:

- USDC: This is the APY from the Pickle Finance USDC jar
- APY: All the rewards are multiplied and given in uAR
- UBQ: The deposit fee gets converted to uAR when you withdraw
- uAD: Match 50% of the USDC deposit and you get an extra 50% boost

**Comment by 0x4007** [comment]
Pretty sure @chriswudev finished this successfully.
