### ISSUE TITLE
TWAP -> Spot Price on UI

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#36]
I think users are more interested to see the spot price vs the time weighted average price on the UI. We should change it! Spot means actual current price.

**Comment by Zequez** [comment]
Isn't the TWAP price the one that determines the debt cycle though? I would think it's quite an important number, considering you aren't allowed to sell uAR if TWAP < 1

**Comment by 0x4007** [comment]
Lets highlight spot price because thats what people are conflating the TWAP with. 

So spot in big numbers and then TWAP in small numbers below?

**Comment by Zequez** [comment]
But spot price you mean the price of uAD - 3CRV as shown in Curve? @pavlovcik

**Comment by sergfeldman** [comment]
Done
