### ISSUE TITLE
Dynamically Read Boost Amounts

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#37]
The boost amounts don't appear to be correct. These should be read dynamically from the contract.

https://github.com/ubiquity/uad-contracts/blob/fffc20f7432da7dee273a11900e45c30fb89cf65/contracts/YieldProxy.sol#L27-L30

```solidity
    uint256 public constant BONUS_YIELD_MAX = 10000; // 1000 = 10% 100 = 1% 10 = 0.1% 1 = 0.01%
    uint256 public bonusYield; //  5000 = 50% 100 = 1% 10 = 0.1% 1 = 0.01%
    uint256 public constant FEES_MAX = 100000; // 1000 = 1% 100 = 0.1% 10 = 0.01% 1 = 0.001%
    uint256 public constant UBQ_RATE_MAX = 10000e18; // 100000e18 Amount of UBQ to be stake to reduce the deposit fees by 100%
```

_Originally posted by @pavlovcik in https://github.com/ubiquity-vercel/uad-ui/issues/17#issuecomment-950552839_

**Comment by Zequez** [comment]
Thy are actually read form the contract.
