### ISSUE TITLE
New DebtCoupons UI

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#38]
So in accordance to the specs to mint uAR directly from the dashboard, I took the liberty to rework the existing Debt Coupons UI and integrate all the new upcoming features too. It's still a WIP and I'll be working on creating a bunch of sub-tasks to make the building process clearer and allow us to distribute the load with @chriswudev or anyone who wants to contribute.

<img width="585" alt="Captura de Tela 2021-10-25 às 09 30 06" src="https://user-images.githubusercontent.com/126037/138719085-9cdcbb46-6069-4f42-a18c-f2b24a795768.png">

## Sub-tasks

- https://github.com/ubiquity/uad-ui/issues/50
- https://github.com/ubiquity/uad-ui/issues/51
- https://github.com/ubiquity/uad-ui/issues/54
- https://github.com/ubiquity/uad-ui/issues/55
- https://github.com/ubiquity/uad-ui/issues/56
- https://github.com/ubiquity/uad-ui/issues/57
- https://github.com/ubiquity/uad-ui/issues/58
- https://github.com/ubiquity/uad-ui/issues/59
- https://github.com/ubiquity/uad-ui/issues/60

**Comment by 0x4007** [comment]
We should definitely explore some d3.js action when we have some time for custom charting/visualizations! Also I think `uDEBT` looks better than `uDebt` as a heads up

**Comment by 0x4007** [comment]
Also @Zequez I encourage you to work with April to set up bounties so we can have some new people from the community come contribute code. Generally speaking we can be very generous with `UBQ` (we print it out of thin air, more or less) then less generous with `uAR`, then `uAD` then lastly stables like `DAI/USDC/USDT`

**Comment by Zequez** [comment]
> We should definitely explore some d3.js action when we have some time for custom charting/visualizations! Also I think `uDEBT` looks better than `uDebt` as a heads up

It would be interesting to see a chart of the TWAP price going up/down to see the debt cycle history.

**Comment by 0x4007** [comment]
So uDEBT doesn't have a depreciating rate in case it isn't clear. It holds its value until the moment it expires in six months. 

![image](https://user-images.githubusercontent.com/4975670/149848823-4f59665d-5533-4d94-96df-bf0704fe6515.png)

**Comment by 0x4007** [comment]
Can somebody explain the math to me here, doesn't seem right!

![image](https://user-images.githubusercontent.com/4975670/149848921-0a68ed6d-9f22-4f08-8c8b-21a41b108c02.png)

**Comment by Zequez** [comment]
I don't think the contracts are actually connected yet, so it might just be a mock value.

**Comment by 0x4007** [comment]
@Zequez @sergfeldman the subtasks all look complete. I don't understand the status

> ## Sub-tasks
> * [New DebtCoupon UI - Build static UI #50](https://github.com/ubiquity/ubiquity-dollar-development/issues/50)
> * [New DebtCoupons UI - Parameterize component #51](https://github.com/ubiquity/ubiquity-dollar-development/issues/51)
> * [New DebtCoupon UI - Ensure thousand-separator for all numbers #54](https://github.com/ubiquity/ubiquity-dollar-development/issues/54)
> * [New DebtCoupon UI - Show expected uAR and uDEBT to be received accordingly #55](https://github.com/ubiquity/ubiquity-dollar-development/issues/55)
> * [New DebtCoupon UI - Use the loaded contracts from context #56](https://github.com/ubiquity/ubiquity-dollar-development/issues/56)
> * [New DebtCoupon UI - Automatically max the uBOND and uAR inputs to the max amounts on the user balance #57](https://github.com/ubiquity/ubiquity-dollar-development/issues/57)
> * [New DebtCoupon UI - uDEBT indicator on the uAR swap should change with the uAR input #58](https://github.com/ubiquity/ubiquity-dollar-development/issues/58)
> * [New DebtCoupon UI - Fixes to the uDEBT table #59](https://github.com/ubiquity/ubiquity-dollar-development/issues/59)
> * [New DebtCoupon UI - TWAP price bar specification #60](https://github.com/ubiquity/ubiquity-dollar-development/issues/60)

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?
