### ISSUE TITLE
booster values UX improvement

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#41]
yyctrader recommends to prominently display while typing in the field "you need X UBQ for 0% fee OR on the uAD side the same thing for max boost"

**Comment by Zequez** [comment]
<img width="890" alt="Screen Shot 2022-04-15 at 12 02 17" src="https://user-images.githubusercontent.com/126037/163586949-b61e6ccf-9942-4adc-a59d-13ecb6ed9755.png">

Quickly added it on the placeholder.

**Comment by Zequez** [comment]
Gonna be merged [as part of the layout update ](https://github.com/ubiquity/uad-ui/pull/83)
