### ISSUE TITLE
Update uAD-3crv LP token ratio

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#43]
`0.7562534324`

`40,703.649892218079569281/53,822.763838` from this deposit https://etherscan.io/tx/0xf6fb1446a0a87d139231f40f52398326e9009630a8187c75717b066a26557361

**Comment by Zequez** [comment]
I shall research how to get that number on-the-fly first.

**Comment by Zequez** [comment]
For the record, this is used on the [DepositShare component](https://github.com/ubiquity/ubiquity-dollar/blob/development/components/staking/DepositShare.tsx#L33) for the APY calculation.

**Comment by 0x4007** [comment]
bounty hunter should dynamically figure out the dollar value of the uAD-3crv LP tokens so that we can accurately display the Bonding Position ID's value in the UI

**Comment by 0x4007** [comment]
> For the record, this is used on the [DepositShare component](https://github.com/ubiquity/uad-ui/blob/main/components/DepositShare.tsx) for the APY calculation.

this is no longer current @Zequez please update your comment and subsequently this one.

**Comment by Zequez** [comment]
> > For the record, this is used on the [DepositShare component](https://github.com/ubiquity/uad-ui/blob/main/components/DepositShare.tsx) for the APY calculation.
> 
> this is no longer current @Zequez please update your comment and subsequently this one.

Updated, the component is still using a hardcoded LP ratio value but [it's on `components/staking/DepositShare.tsx`](https://github.com/ubiquity/ubiquity-dollar/blob/development/components/staking/DepositShare.tsx#L33)

**Comment by 0x4007** [comment]
I was just researching this right now and there is a method to query directly on the metapool `calc_token_amount` which gives an imprecise value "to prevent frontrunning" 

https://github.com/curvefi/curve-metapool/blob/bea8df855866cf170d2f197071e80fbc47483656/vyper/stableswap.vy#L168

https://curve.readthedocs.io/factory-deposits.html

Here's my quick test

On crv.to presumably this is correct?

![crvto](https://user-images.githubusercontent.com/4975670/181625353-ea358c4a-42a4-4e26-9535-df99d1efec62.png)

On etherscan

![photo_2022-07-29 03 52 36](https://user-images.githubusercontent.com/4975670/181625381-4b51344c-2c81-465c-a048-63d4277599a9.jpeg)

I asked zashton from crv.to for his input no response yet 

<img width="492" alt="image" src="https://user-images.githubusercontent.com/4975670/181625554-90c96a58-78de-4fee-bb4f-f982c9912c88.png">

**Comment by super-dev0728** [comment]
Hello. So was this issue solved?

**Comment by sergfeldman** [comment]
@super-dev0728 This issue is in progress.

**Comment by super-dev0728** [comment]
Thanks for your email.
Could you tell me what issues are available?

Thanks

**Comment by 0x4007** [comment]
I actually handled this by hardcoding an updated value in my latest merge into `development` #244 

We should update this issue to read the proper value from Curve smart contracts though.
