### ISSUE TITLE
Verify `sharesResults` will support arbitrary lockup weeks durations

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#44]
What's up with these values? There should be people with different amounts in the future @Zequez @chriswudev

_Originally posted by @pavlovcik in https://github.com/ubiquity/uad-ui/pull/17#discussion_r739053413_

**Comment by Zequez** [comment]
That's just to show the APY at different weeks; it's not part of the UI just part of the logBondingUbqInfo function for the sake of developing and debugging. We do allow arbitrary weeks. So I'm closing this.
