### ISSUE TITLE
Cleanup `Environments` / Deploy develop branch to staging domain

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#45]
This will be fantastic for the growth team to get sneak previews easily by clicking the environments links for the latest beta UIs. To minimize confusion, we should delete the redundant/deprecated environments, but, I'm not doing it right now because I'm not 100% sure where the extras came from (would like to properly rename to keep this repo clean!)

![image](https://user-images.githubusercontent.com/4975670/139411576-c02bdc56-ac25-4671-b8b9-444385ea3502.png)

**Comment by Zequez** [comment]
I propose we deploy the develop branch to develop.uad.fi so we can use it as both preview and staging for QA. This is something that needs to be configured on Vercel; so it's for @pavlovcik

**Comment by 0x4007** [comment]
* Use a secondary internet browser to login to github with the credentials I shared in the group chat, then login with github on vercel.

* I’m making a staging environment work (for free) you just need to click this button to update the @ubiquity-vercel fork of the repo in order to have it run on staging.

* The only kind of major issue is that we haven't updated the Vercel deployment (uad.ubq.fi) since before turned it into a monorepo and totally refactored the build process to yarn ape so the build is failing on Vercel

https://github.com/ubiquity-vercel/ubiquity-dollar-staging/invitations

**Comment by 0x4007** [comment]
I just realized that the build needs to be solved before GitHub repo UI will show the environments. Because of this, the issue technically is not finished.

<img width="390" alt="image" src="https://user-images.githubusercontent.com/4975670/166144320-87413996-3539-419c-a488-0d33947cf180.png">

:(

**Comment by 0x4007** [comment]
> I propose we deploy the develop branch to develop.uad.fi so we can use it as both preview and staging for QA. This is something that needs to be configured on Vercel; so it's for @pavlovcik

Bad news is that the domain name `ubq.fi` and all of its subdomains can only be linked to a single Vercel account.

We currently have two Vercel accounts to consider:

1. @ubiquity-vercel 
* * owns ubiquitydao.xyz
2. @pavlovcik 
* * owns ubq.fi

I'm not keen on setting up this one because its on the @Ubiquity organization account and Vercel wants to charge money for it :( So instead, I suggest that when QA needs to be done, to simply pull the changes over to staging by pressing this button!

<img width="467" alt="image" src="https://user-images.githubusercontent.com/4975670/166822220-bcbb3669-1aeb-416f-879a-729b2b0b3e20.png">

https://github.com/ubiquity-vercel/ubiquity-dollar-staging

---

I vaguely recall a workaround for Vercel where I can set up all the deploys/environments of the repo on a personal account, and then transfer the repository to the organization and it still works for free I'm pretty sure lol

**Comment by sergfeldman** [comment]
The Staging environment https://ubiquity-dollar-staging.vercel.app/
