### ISSUE TITLE
Fix CodeQL Security Issues

### ISSUE THREAD

**Issue by FibrinLab** [ubiquity/uad-ui#456]
> @pavlovcik I noticed CodeQL scanning revealed 8 alerts with 2 high severity security issues. How do we address this?

Post a new issue it'll be a new bounty

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquity-dollar/issues/453#issuecomment-1371934107_

8 new alerts including 2 high severity security vulnerabilities

Security Alerts:

2 high
6 medium

**Comment by FibrinLab** [comment]
The security issues are all found in the typescript files. Modifications would be required so they are security compliant.

**Comment by FibrinLab** [comment]
Almost done. Fixing Regex issues

**Comment by 0x4007** [comment]
@FibrinLab please share your wallet address here thanks!

**Comment by FibrinLab** [comment]
0x43BbdE754e2e4e8A3b1282D1037Ce1a1B7c577C2

**Comment by 0x4007** [comment]
> 0x43BbdE754e2e4e8A3b1282D1037Ce1a1B7c577C2

https://etherscan.io/tx/0x5b87600fcce34317fec06e9d70f817418ceeda2b2915667f7e6a2a1ca282c995
https://etherscan.io/tx/0xdcdab36fe01b6ffedf7699e4f80801c9f5b39daa9def68faafd258f4bad2d900

**Comment by FibrinLab** [comment]
> > 0x43BbdE754e2e4e8A3b1282D1037Ce1a1B7c577C2
> 
> 
> 
> https://etherscan.io/tx/0x5b87600fcce34317fec06e9d70f817418ceeda2b2915667f7e6a2a1ca282c995
> 
> https://etherscan.io/tx/0xdcdab36fe01b6ffedf7699e4f80801c9f5b39daa9def68faafd258f4bad2d900

@pavlovcik Transaction pending. Not yet mined

**Comment by 0x4007** [comment]
https://etherscan.io/tx/0xf595fb81ed2d12514f0dd609297f50f08c6d43217bc553c9dfc49c2f66ff25f2
