### ISSUE TITLE
Map ubq.eth ENS to appropriate smart contracts (e.g. uad-token.ubq.eth, ubq-token.ubq.eth, uar-token.ubq.eth, bonding.ubq.eth etc)

### ISSUE THREAD

**Issue by marcomow** [ubiquity/uad-ui#46]

**Comment by Zequez** [comment]
I don't have the credentials to manage the ubq.fi domain, @pavlovcik this is for you.

**Comment by 0x4007** [comment]
@Zequez it was an incorrect title its actually to give vanity addresses for our [smart contracts](https://dao.ubq.fi/smart-contracts).

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?
