### ISSUE TITLE
New DebtCoupon UI - Automatically max the uBOND and uAR inputs to the max amounts on the user balance

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#57]
<img width="859" alt="Captura de Tela 2021-11-30 às 11 28 41" src="https://user-images.githubusercontent.com/126037/144068189-a6863540-fb5c-4780-af09-d68a890b8345.png">

So that should automatically max to `1000` whenever we try to input a larger amount. (same for uAR)

Another option would be to disable the redeem button if the amount is <= 0 or > of the total balance. Either way would work.

**Comment by marcomow** [comment]
add toast notification to alert user that input exceeding max availability was overwritten https://materializecss.com/toasts.html
