### ISSUE TITLE
New DebtCoupon UI - TWAP price bar specification

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#60]
Currently the TWAP price bar looks like this:

<img width="985" alt="Captura de Tela 2021-11-30 às 11 52 10" src="https://user-images.githubusercontent.com/126037/144069913-57dfce24-e84e-4942-8cfb-afad09ac316d.png">

- If the TWAP price is $1 the bar should be right in the middle
- If TWAP price is <$1
  - The bar should be moved to the left proportionally (maxed at 20% left-positioned)
  - Price should appear on the left side, text on right side
  - Price side should have a redish background; component a reddish style
  - Bar text should read "Pump cycle started X days ago"
  - Bottom text should read "Burn uAD for debt coupons and help pump the price back up"
  - Coupons controls should be disabled; uAD burning controls should be enabled and appear first on the component.
- If TWAP price is >$1
  - The bar should be moved to the right proportionally (maxed at 80% left-positioned)
  - The price should appear on the right side instead of the left side
  - Price side should have a greenish background; component a greenish border
  - Bar text should read "Redeeming cycle started X days ago"
  - Bottom text should read "Time to redeem debts coupons and help move the price down"
  - uAD burning controls should be disabled; Coupons controls should be enabled and appear first on the component.

**Comment by Zequez** [comment]
<img width="614" alt="Captura de Tela 2021-12-08 às 14 09 04" src="https://user-images.githubusercontent.com/126037/145252272-4ceaaee2-d1cc-40c6-83f1-383165603497.png">

What about something like this?

**Comment by marcomow** [comment]
Looks good!
