### ISSUE TITLE
Segment dApp Into Separate Views

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/uad-ui#61]
We should start isolating functionalities of our protocol into different views

![image](https://user-images.githubusercontent.com/4975670/146270469-507f8897-855a-4162-b1db-41fec3eca681.png)
[https://app.olympusdao.finance/#/dashboard](https://app.olympusdao.finance/#/dashboard)

**Comment by Zequez** [comment]
<img width="930" alt="Captura de Tela 2021-12-28 às 13 30 14" src="https://user-images.githubusercontent.com/126037/147586954-6ea5994b-d037-4a60-b12c-67fbb953be3f.png">

I've been thinking something like this. We could add icons and play with the styles.

**Comment by 0x4007** [comment]
Would you mind presenting on a call so we can chat through your vision? Generally I trust your judgement regarding the UI design so I'd be happy with run-and-gun. And then we can do minor adjustments afterwards. But would feel more comfortable briefly discussing on a call before you dive in coding

**Comment by marcomow** [comment]
https://github.com/OlympusDAO/olympus-frontend
