### ISSUE TITLE
Launch Party UI - Consolidate information about liquidity pools to be used

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#68]
We need the following information about each pool:

- Token pair
- Pool contract address
- Pool contract link (Uniswap/Sushiswap?
- Logo (PNG or SVG work fine)
- How do we select it on the bonding contract? With the address? With an ID?

**Comment by Zequez** [comment]
@pavlovcik what's the status of this information?

**Comment by 0x4007** [comment]
> We need the following information about each pool:
> 
> * Token pair

"pool2"
uAR-ETH

"pool1"
uAD-LUSD
uAD-OHM
uAD-MIM
uAD-UST
uAD-FRAX
uAD-FEI
uAD-DOLA
uAD-DAI
uAD-USDC
uAD-USDT
uAD-ALUSD

> * Pool contract address

I will need to make all the markets on Uniswap 😖

> * Pool contract link (Uniswap/Sushiswap?

I will need to make all the markets on Uniswap

> * Logo (PNG or SVG work fine)

I will need to scrape all the icons from coingecko etc

> * How do we select it on the bonding contract? With the address? With an ID?

As far as I'm aware, these sorts of things are identified with addresses typically in smart contract world.

**Comment by Zequez** [comment]
I'm closing this because the information is already gathered, what's missing is just creating the pools and adding the addresses to the configuration. There is a [checklist on the sub-app Notion page](https://www.notion.so/ubiquitydao/Launch-Party-eefae32d68484de3931d036417382718#50f27eebee1642a69e0220504026df5b) @pavlovcik  but I'll create a new issue
