### ISSUE TITLE
Launch Party UI - Contract interface

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#73]
- Deposit function that takes the token pair and an amount
- A way to calculate APY for each token pair
- A way to read the progress of the bonding period (get the end block and the total uAR rewarded and the claimable uAR at the moment)
- A way to claim all the rewards at the same time on a single transaction

Taggin @zapaz so we can discuss here.

**Comment by zapaz** [comment]
a test smartcontract has been initialized , some function implemented, mainly deposit 

repo here : https://github.com/ubiquity/simple-bond

first deploy : https://rinkeby.etherscan.io/address/0xa802e065da87bb249d35e3a22df58cfa8f268e03#readContract

**Comment by zapaz** [comment]
New contract here : https://rinkeby.etherscan.io/address/0x455D264a380f38D07a3DE725eB0362b408C9657a#readContract

Some tests there : 
https://github.com/ubiquity/simple-bond/blob/main/tests/SimpleBond.test.ts
