### ISSUE TITLE
Launch Party UI - QA testing checklist

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#78]
Setting up the project for easier initialization.

There is a launch-party branch on uad-ui on uad-contracts and on the-ubiquity-stick repositories.

1. `git clone https://github.com/ubiquity/uad-ui`
2. `cd uad-ui`
3. `git checkout launch-party`
4. `yarn`
5. `yarn contracts:init`
6. Fill the .env file on contracts and the-ubiquity-stick
    1. It’s the same .env except the-ubiquity-stick requires `DEPLOYER_PRIVATE_KEY` (export it from Metamask) because the hardhat.config.ts works differently from the contracts repo
7. `yarn contracts:build`
8. `yarn contracts:node` (this keeps running)
9. (in another terminal after the node is running) `yarn contracts:faucet`
10.` yarn next:dev`

Note: I’m not sure how to get hardhat to make deterministic localhost deployments yet (we all need to use the same test Metamask account for deployment?), so if the addresses on the node are different from the ones on the launch-party/lib/contracts.ts file then change them.

@pavlovcik

**Comment by 0x4007** [comment]
There's an EVM opcode to control the deploy address based on a salt. In the deploy tasks we need to use that opcode instead, basically, afaik.

@zapaz is this something you can do quickly?

**Comment by 0x4007** [comment]
Couldn't get this to work in my call with Concave. We need to setup a meeting this week with you @Zequez and @zapaz with the Concave engineers for a product and code review.

**Comment by Zequez** [comment]
The whole setup changed so this is no longer relevant. The actual testing methodology should go in line with the list of features, so I'm [moving this issue to the documentation.](https://ubiquitydao.notion.site/Launch-Party-eefae32d68484de3931d036417382718) There I list all the sub-components and how they are supposed to work, along with bugs they have or improvements lacking.
