### ISSUE TITLE
Launch Party UI - Create missing pools and add the addresses to the configuration

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#84]
- [ ]  Right now we’ve got only the uAR-WETH pool and the uAR-USDC pool; the following pools contracts need to be created and their addresses added to the UI
    - [ ]  uAD-LUSD
    - [ ]  uAD-OHM
    - [ ]  uAD-MIM
    - [ ]  uAD-UST
    - [ ]  uAD-FRAX
    - [ ]  uAD-FEI
    - [ ]  uAD-DOLA
    - [ ]  uAD-DAI
    - [ ]  uAD-USDT
    - [ ]  uAD-ALUSD

Addresses gotta be added to the `launch-party/lib/pools.ts` file.

**Comment by 0x4007** [comment]
I vaguely recall streamlining the launch rollout to just a few of the major stable markets. Also we should only do STABLE-STABLE so we should remove OHM. I'll put more thought into this while I deploy the markets!

**Comment by 0x4007** [comment]
Hotlinked the transactions to mint the new markets on Uniswap V3. You should be able to derive the market address from this info. Pools we should add, and some remarks:

* uAD-ETH // easy oracle, and same/recyclable tech as pool2 ... still pondering this but feels right
* [uAD-LUSD](https://etherscan.io/tx/0xb5eb68786e2914ae976ca51ae4200617fb8a91c7ee90292908deca86e3af0e6c) // fav stable tbh 
* [uAD-DAI](https://etherscan.io/tx/0x0724f1460918ffc046a673f1e81d3f0a2975db982ec73ccf812d93e3b2d0547d) // we're defi native! 
* [uAD-USDC](https://etherscan.io/tx/0x85bd82bf3a0cd3c72adbd759555f464870783df73de9f3647972d2cce9e93f68) // you always gotta have usdc somewhere involved in a stablecoin project
* uAD-FRAX // they are on our cap table, and discussed helping with liquidity

---

Note to self: once the pools have been created, need to navigate to https://etherscan.io/address/0x9a999c8835e975bbcd255d5e9e9a11f59cc58f40#writeContract and `createManagedPool` with `managerFee` of 0

---

I might have messed up the range for `uAD-USDC` you can see the ratios were messed up upon spawning the pool 😓 it's currently set to [0.99980267 USDC - 1.00020265 USDC](https://www.sorbet.finance/#/pools/0xA9514190cBBaD624c313Ea387a18Fd1dea576cbd) the average is `1.00000266 USDC` aka `1.000003 USDC`

**Comment by sergfeldman** [comment]
Waiting for Gelato 
uAD-LUSD
uAD-DAI

Waiting for the decision do/not do 
uAD-ETH
uAD-FRAX

**Comment by 0x4007** [comment]
# Gelato'd
* [uAD-LUSD](https://etherscan.io/tx/0xec506a4de75c4bd1f37815c8c99e8301804a853cbac5b4f55dcd527fbd2b5433)
* [uAD-DAI](https://etherscan.io/tx/0xd4c4f02f0929c5e4d167adbf72ccec1406cb787ceca48f8f0b644269d5c9e0c4)

# Decisions

> Waiting for the decision do/not do
> uAD-ETH

TBD. Haven't had a chance to model out worst case scenarios
> uAD-FRAX

Mostly keen on this after hashing out collaboration details. Sam has been a bit difficult to get in touch with lately so it's been deprioritized. 

## Notes to self
Ref params via etherscan [writeContract](https://etherscan.io/address/0xea1aff9dbffd1580f6b81a3ad3589e66652db7d9#writeProxyContract)
<img width="372" alt="image" src="https://user-images.githubusercontent.com/4975670/167699473-b401b92a-abc5-4f56-b601-b5d3581903dc.png">

**Comment by Zequez** [comment]
Alright, do we add the 2 new pools to the UI and close this issue? So we launch with 3 pool1 and the uAR-WETH as pool2?

**Comment by 0x4007** [comment]
@Zequez lets pass on uAD-FRAX. I [created a Uniswap V2 market](https://etherscan.io/tx/0xbabef0c4aa0487f4e794d241cb754dae85abc38efa23c7a34a81f3437ff92ffe) for uAD-ETH which exists [here](https://etherscan.io/address/0x95e3547d5a326092661f16ec06e6fc5681c8d33c).

It's a Uniswap V2 market as its the most gas efficient for ETH paired markets

**Comment by Zequez** [comment]
Closing for now; if in the future we want to add additional markets, let's create a new issue.
