### ISSUE TITLE
Allow users to explicitly manage their ERC20 tokens allowances

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#85]
Right now most of our contracts ask for the specific allowance needed for the transactions to be done.
Some advocate for setting infinite allowance; others for what we are doing right now. [Both have their pros and cons.](https://kalis.me/unlimited-erc20-allowances/)

So I suggest we allow users to set the allowance themselves (allow them to set to infinity if they want); and maybe even build an UI so they can see the allowances they've got with each of our contracts (and allow them to revoke the allowance too).

**Comment by 0x4007** [comment]
> and maybe even build an UI so they can see the allowances they've got with each of our contracts (and allow them to revoke the allowance too).

https://etherscan.io/tokenapprovalchecker

**Comment by 0x4007** [comment]
> So I suggest we allow users to set the allowance themselves (allow them to set to infinity if they want); 

I was skeptical about Gelato so I manually confirmed my token allowance. Let Metamask handle this, its already a solved problem between my two comments. 

<img width="472" alt="image" src="https://user-images.githubusercontent.com/4975670/166893854-11bf25f4-9d5e-4251-b0d1-435a00a8e15c.png">
