### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/uad-ui#88]
The goal is to have a smooth user experience for the launch

Must have
- [x] #99   
- [x] #84  
- [x] #89 
- [x] #87 
- [x] #36 
- [x] #45
TBD 

To consider 
- [ ] #38 - if close to completion, then take this
- [ ] #19  - if it's done quickly

**Comment by Zequez** [comment]
Just added #89

**Comment by 0x4007** [comment]
Added #99. This is necessary for Vercel to host the new UI. As a result, this issue is mandatory to solve for deployment.
