### ISSUE TITLE
Make account impersonation workflow for testing

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#90]
So there are 2 things here, one is impersonating an address for the sake of reading; and the other is using that as a signed by using the Hardhat impersonation function while working with the local Hardhat node. The first one is quite straightforward, and the second one needs a little bit of research.

**Comment by sergfeldman** [comment]
1-hour research 
1-2 days, check the estimate after the research

**Comment by Zequez** [comment]
Alright, so it's possible to impersonate an account by bypassing Metamask and creating a JsonRpc provider directly connected to the localhost Hardhat node. The only difference is that you won't get prompted to sign transactions.

To implement this I've gotta refactor the Web3provider/wallet/signer hooks. I've already started today, and it's likely that I can finish this tomorrow.
