### ISSUE TITLE
Check the top menu on mobile 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/uad-ui#92]
Please, check that the top menu on mobile works properly 
If there are issues, then fix them

Pages - all pages on https://ubq.fi/
Device - any mobile phone on Android or iOS
Browser - Chrome (latest version)

**Comment by sergfeldman** [comment]
![3](https://user-images.githubusercontent.com/15567379/164529914-6b1e388f-2d27-4253-acce-d61d56fb099b.jpg)

**Comment by sergfeldman** [comment]
The top menu on mobile must open the same points that are available in the header on the desktop: 
[Documentation] (https://dao.ubq.fi/docs)
[Community] (https://discord.gg/SjymJ5maJ4)

**Comment by 0x4007** [comment]
Nice find! Didn't realize that doesn't work. I assume it's a z-index issue. I'm mobile now otherwise I would check the code

**Comment by sergfeldman** [comment]
https://makerdao.com/en/ Original page

**Comment by sergfeldman** [comment]
1-2 days

**Comment by 0x4007** [comment]
It only had two links which are also available on the footer, so I simply hid the sandwich menu. I think its fine!
