### ISSUE TITLE
Check the favicon on all pages 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/uad-ui#94]
Currently, on the page https://landing.ubq.fi/en/ the favicon of the tab in the browser looks differently from the favicon on other pages.
Please, check that the favicons on all pages are the same.
If needed, then update so that all the pages have the same favicon.

**Comment by sergfeldman** [comment]
![5](https://user-images.githubusercontent.com/15567379/164533713-9dad2138-fbf0-45a1-8cdb-4869bbbf7088.JPG)

**Comment by sergfeldman** [comment]
![6](https://user-images.githubusercontent.com/15567379/164533937-4f1429c7-6f1b-42e0-871f-1730c76a331c.JPG)

**Comment by 0x4007** [comment]
The landing page has gotten the least attention and updates as you can see with all these minor issues. Will also need to rewrite the content and update the icons in the page!

**Comment by sergfeldman** [comment]
https://landing.ubq.fi/en/ is not available now

**Comment by sergfeldman** [comment]
https://github.com/pavlovcik/uad-docs/blob/593df1885c1c26ac722399328aaceafc53644f0a/public/sizes/resizer.sh resizer for images

**Comment by 0x4007** [comment]
Landing page currently not in this repo but the issue has been solved so I'm closing manually.
