### ISSUE TITLE
Set up redirect for www.ubq.fi

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/uad-ui#95]
Please, set up redirect for www.ubq.fi

From variations with www in domain name 
https://www.ubq.fi 
http://www.ubq.fi

to https://ubq.fi

![7](https://user-images.githubusercontent.com/15567379/164535857-7fb18c21-d625-4189-9729-8231338f98b5.JPG)
![8](https://user-images.githubusercontent.com/15567379/164535860-684c9c96-42b4-47a0-b375-eef777f3c6a9.JPG)

**Comment by 0x4007** [comment]
I can add you to the cloudflare dns config. Just let me know your information.  I can't find where to add you from mobile so perhaps this can be assessed in a standup when I'm on my Mac.

**Comment by sergfeldman** [comment]
The input from @Zequez to review configuration on Vercel https://vercel.com/blog/redirecting-domains

**Comment by sergfeldman** [comment]
Fixed by Cloudflare Page Rules
https://support.cloudflare.com/hc/en-us/articles/4729826525965-Configuring-URL-forwarding-or-redirects-with-Page-Rules
https://developers.cloudflare.com/pages/how-to/www-redirect/
https://www.maxivanov.io/domain-and-path-redirects-with-cloudflare/

**Comment by sergfeldman** [comment]
It is required to set up both the Page Rule and the DNS record to fix it
