### ISSUE TITLE
Establish/update 404 page 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/uad-ui#96]
Please, establish/update a regular 404 page where a user gets clear information in the same style 

Check on cases
https://ubq.fi/a
https://dao.ubq.fi/d
https://uad.ubq.fi/a 

TBD

![9](https://user-images.githubusercontent.com/15567379/164536474-ef7c7752-bc31-433e-9653-764907a4d4e1.JPG)

**Comment by sergfeldman** [comment]
![10](https://user-images.githubusercontent.com/15567379/164536732-b6c6230a-9c3e-460e-a96a-cd8d5f0368e5.JPG)
![12](https://user-images.githubusercontent.com/15567379/164537065-d8899c5b-7897-4603-9b9d-7fac4b27a92f.JPG)

**Comment by sergfeldman** [comment]
![13](https://user-images.githubusercontent.com/15567379/164537604-1de88a04-c90a-4333-8a04-ffe4b7c14492.JPG)

**Comment by 0x4007** [comment]
Nice attention to details! This is a vercel / nextjs deployment so will need to check their docs to produce a 404 page

**Comment by codeawayaks** [comment]
You can assign this to me.

**Comment by sergfeldman** [comment]
> You can assign this to me.

@codeawayaks You commented on 20+ GitHub issues that you want to take it. 
One developer should solve one bounty at a time to minimize blocking other developers to effectively move forward.
Which 1 bounty do you want to take?

**Comment by ryzhak** [comment]
Hi, I can take this one

A few questions:

1. How about this 404 layout?
<img width="894" alt="Screenshot 2022-11-07 at 13 37 16" src="https://user-images.githubusercontent.com/6339689/200292463-3239808b-2258-4aec-8a67-feec95105737.png">

2. Where is the repo for https://dao.ubq.fi/ ? It seems this website is somehow compiled from notion but I can't find the sources.
```
Project files for https://ubq.fi => https://github.com/ubiquity/ubq.fi
Project files for https://uad.ubq.fi/ => https://github.com/ubiquity/ubiquity-dollar/tree/development/packages/dapp
Project files for https://dao.ubq.fi => ?
```

3. https://ubq.fi is a plain html + js file so there are 2 ways to create 404 page:
a) JS side, on page load redirect any none-empty route to 404.html
b) Server side, redirect any none-empty route to 404.html page
For simplicity we should go with JS redirect, right?

**Comment by 0x4007** [comment]
1. I think its fine but I would recommend you try to not introduce too much custom styling. Try and keep the design implementation super basic because I'll very likely want to go in and personally iterate when I have extra time.
2. This is a bit messy (we might actually have to redo this code) due to some infrastructure problems - it just hasn't been prioritized. Its hosted on my personal GitHub because Vercel charges money for Organization accounts https://github.com/pavlovcik/uad-docs
3. Either should be fine but I would argue that the JS redirect would be more complicated. There isn't a concept of "views" as you observed its static.

---

I just realized that we can probably redeploy the Notion CMS code on Netlify so that we don't have this limitation @0xcodercrane ?

**Comment by ryzhak** [comment]
@pavlovcik 

ok, you can assign this issue to me

**Comment by cuddle-dev** [comment]
> 1. I think its fine but I would recommend you try to not introduce too much custom styling. Try and keep the design implementation super basic because I'll very likely want to go in and personally iterate when I have extra time.
> 2. This is a bit messy (we might actually have to redo this code) due to some infrastructure problems - it just hasn't been prioritized. Its hosted on my personal GitHub because Vercel charges money for Organization accounts https://github.com/pavlovcik/uad-docs
> 3. Either should be fine but I would argue that the JS redirect would be more complicated. There isn't a concept of "views" as you observed its static.
> 
> I just realized that we can probably redeploy the Notion CMS code on Netlify so that we don't have this limitation @0xcodercrane ?

yes we can.

**Comment by 0x4007** [comment]
Looks like all the 404 pages are functional good work @ryzhak -- can you accept DAI? If so, please share your DAI + UBQ (self hosted) wallet address!

**Comment by ryzhak** [comment]
@pavlovcik 

> can you accept DAI?

yes

my wallet: [0x165343c045a00770b61DbCa01956590cC6005666](https://etherscan.io/address/0x165343c045a00770b61DbCa01956590cC6005666)

**Comment by 0x4007** [comment]
Thanks for your service! https://etherscan.io/tx/0xcfb279e7d5ed2f570a27676b6639df0dfd5aa7dad8d07e400228b04e2ebc2b1d
https://etherscan.io/tx/0xe0ca7491414481ec15d2de7b26a46c290a071129d8ed679b1de75903920c4e3a
