### ISSUE TITLE
Figure out the way how to maintain styles on the website after updates of Travis`s project 

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/uad-ui#97]
Figure out the way how to maintain styles on the website after updates of Travis`s project 
https://github.com/transitive-bullshit/nextjs-notion-starter-kit 

First of all check the version before this commit 
 https://github.com/transitive-bullshit/nextjs-notion-starter-kit/commit/679131ad22b0aa581ed9460096f8df12a02e5029

**Comment by sergfeldman** [comment]
@ubq-cw 

1. Find the root cause 
- First of all, check the styles if use the version of Next.js Notion Starter Kit before this commit
https://github.com/transitive-bullshit/nextjs-notion-starter-kit/commit/679131ad22b0aa581ed9460096f8df12a02e5029
- If the previous action doesn`t help, analyze the difference between the current version on Production and the new version with style issues.
- If the previous actions don`t help, look for other ways to identify the root cause.
- When find, describe the root cause in a comment on this issue. 

2. Come up with the solution 
- Suggest options on how to maintain styles on the website after updates of the third-party Next.js Notion Starter Kit

**Comment by 0x4007** [comment]
This issue is on the wrong repo. The correct repo is here https://github.com/pavlovcik/uad-docs

**Comment by sergfeldman** [comment]
At the moment, I don`t have a way to transfer this issue (please, look at the screen).
I suggest waiting for Chris' fix, then decide whether to create a separate issue in the correct repository.

![1](https://user-images.githubusercontent.com/15567379/165796565-ca5df32e-a194-4f20-8038-2b3b0a59b86b.JPG)
 to the repo https://github.com/pavlovcik/uad-docs

![2](https://user-images.githubusercontent.com/15567379/165797969-c330ff6c-c35d-4c0d-aa48-38b80e697f68.JPG)

**Comment by 0x4007** [comment]
Attempted another merge from `transitive-bullshit:main` and seems like there's more updates that also are a conflict to run.

https://github.com/pavlovcik/uad-docs/pull/7

I wonder if its cleaner to fork from their repo and manually add our changes on top, instead of trying to directly merge.

**Comment by sergfeldman** [comment]
Fixed in the code 
Check the functionality in Master 
1-2 days
